### PR TITLE
fix: the git commit hash in the docker is empty string

### LINKED ISSUE #1438: Bug: the commit_hash in the demo is empty string
# Bug report

## Describe the bug

The commit_hash is "", when requesting the online demo.

## How to Reproduce

`
curl 139.217.190.60/apisix/admin/tool/version -v
`

The response:

```
"code":0,"message":"","data":{"commit_hash":"","version":"master"},"request_id":"a96d8d8f-e0af-4a17-8caa-d4a7bff03a3b"}
```

## Expected behavior

Return the correct commit_hash.

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
close #1438

___
### Bugfix
- Description
In the docker build, the compressed package of github is directly downloaded, which does not contain git information, that causes the git commit hash to be empty string

- How to fix?
use git repo source code to build docker image.

### CODE REVIEW

File: api/VERSION [hunk 1]
```diff
@@ -1 +1 @@
-master
+2.3
```
Comment (imjoey) [inline api/VERSION:1]: @nic-chen  Any reason to change this to `2.3`? IMHO, we shall keep using `master` in master branch.

File: Dockerfile [hunk 2]
```diff
@@ -19,9 +19,10 @@ FROM alpine:latest as pre-build
 ARG APISIX_DASHBOARD_VERSION=master
 
 RUN set -x \
-    && wget https://github.com/apache/apisix-dashboard/archive/${APISIX_DASHBOARD_VERSION}.tar.gz -O /tmp/apisix-dashboard.tar.gz \
-    && mkdir /usr/local/apisix-dashboard \
-    && tar -xvf /tmp/apisix-dashboard.tar.gz -C /usr/local/apisix-dashboard --strip 1
+    && apk add --no-cache --virtual .builddeps git \
+    && git clone https://github.com/apache/apisix-dashboard.git -b ${APISIX_DASHBOARD_VERSION} /usr/local/apisix-dashboard \
+    && cd /usr/local/apisix-dashboard && git clean -Xdf \
+	&& rm -f ./.githash && git log --pretty=format:"%h" -1 > ./.githash
```
Comment (imjoey) [inline Dockerfile:25]: Please fix code style here. Thanks.

File: api/test/shell/manager_smoking.sh [hunk 3]
```diff
@@ -52,6 +52,12 @@ else
 	    echo "no Version output"
 	    exit 1
 	fi
+   # Version output
```
Comment (imjoey) [inline api/test/shell/manager_smoking.sh:55]: Please fix code style here.

**Review by imjoey — CHANGES_REQUESTED** [review]

File: api/VERSION (hunk 1 above)
Comment (nic-chen) [reply api/VERSION:1]: @imjoey  
it will show warning notification when dashboard version not matching APISIX(#1435).
so we should make it consistent with APISIX, use the last released version as the version number of the master. and we also have git commit hash to distinguish the specific build.

File: Dockerfile (hunk 2 above)
Comment (nic-chen) [reply Dockerfile]: fixed.

File: api/test/shell/manager_smoking.sh (hunk 3 above)
Comment (nic-chen) [reply api/test/shell/manager_smoking.sh]: fixed.

File: api/VERSION (hunk 1 above)
Comment (imjoey) [reply api/VERSION:1]: > @imjoey
> it will show warning notification when dashboard version not matching APISIX(#1435).
> so we should make it consistent with APISIX, use the last released version as the version number of the master. and we also have git commit hash to distinguish the specific build.

@nic-chen OK, I see. the version here indicates the matched version of APISIX. Thanks.

**Review by imjoey — APPROVED** [review]
/lgtm

Thanks.

**Review by starsz — APPROVED** [review]

**Comment by imjoey** [comment]
Hi. @juzhiyuan @starsz , this PR needs to be backported to v2.4 branch for release 2.4.
