### PR TITLE
bugfix: dashboard 2.0 failed to fetch ssl certificate not found 

### LINKED ISSUE #697: dashboard 2.0 failed to fetch ssl certificate not found
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

dashboard 2.0 
centos 7
chrome 83

- What happened?
If possible, provide a way to reproduce the error.
证书已经上传了，但是错误日志中报下面这个截图
image

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by nic-chen**
close #697

### CODE REVIEW

File: api/test/e2e/ssl_test.go [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+			caseDesc:     "create ssl fail - key and cert not match",
+			Object:       MangerApiExpect(t),
+			Method:       http.MethodPost,
+			Path:         "/apisix/admin/ssl",
+			Body:         string(invalidBody),
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusBadRequest,
+		},
+		{
+			caseDesc:     "create ssl successful",
```
Comment (juzhiyuan) [inline api/test/e2e/ssl_test.go:57]: `successfully`, *adv*

File: api/internal/handler/ssl/ssl.go [hunk 2]
```diff
@@ -147,6 +147,7 @@ func (h *Handler) Create(c droplet.Context) (interface{}, error) {
 	}
 
 	ssl.ID = input.ID
+	ssl.Status = 1
```
Comment (moonming) [inline api/internal/handler/ssl/ssl.go:150]: Is this the cause of the bug?  Can you explain the reason?

File: .github/workflows/e2e-test-backend.yml [hunk 3]
```diff
@@ -28,7 +28,10 @@ jobs:
           sleep 5
           docker logs docker_managerapi_1
 
+      - name: set hosts
+        working-directory: ./api/test/e2e
+        run: echo "127.0.0.1 www.test2.com" | sudo tee -a /etc/hosts
```
Comment (moonming) [inline .github/workflows/e2e-test-backend.yml:33]: why need to change local file?

File: api/test/e2e/ssl_test.go [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
+		},
+		{
+			caseDesc:     "delete ssl",
+			Object:       MangerApiExpect(t),
+			Method:       http.MethodDelete,
+			Path:         "/apisix/admin/ssl/1",
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
```
Comment (moonming) [inline api/test/e2e/ssl_test.go:115]: We need to check again after delete route and ssl cert

**Review by moonming — CHANGES_REQUESTED** [review]

File: api/internal/handler/ssl/ssl.go (hunk 2 above)
Comment (nic-chen) [reply api/internal/handler/ssl/ssl.go:150]: yes, it's the cause.
That is because in Go if does not explicitly assign a value, it will automatically assign a 0 value. So the SSL is disable.

File: .github/workflows/e2e-test-backend.yml (hunk 3 above)
Comment (nic-chen) [reply .github/workflows/e2e-test-backend.yml:33]: That's because we can't make https request like this:

```
curl https://127.0.0.1:9443  -H 'Host: www.test2.com'
```

the SSL of www.test2.com will not match by this way. so need to set host and request www.test2.com directly.

File: api/test/e2e/ssl_test.go (hunk 4 above)
Comment (nic-chen) [reply api/test/e2e/ssl_test.go:115]: ok

File: api/internal/handler/ssl/ssl.go (hunk 2 above)
Comment (membphis) [reply api/internal/handler/ssl/ssl.go:150]: that is the magic number. we should use a `const` variable for a better name.

File: .github/workflows/e2e-test-backend.yml (hunk 3 above)
Comment (membphis) [reply .github/workflows/e2e-test-backend.yml:33]: `curl --resolve 'www.test2.com:9443:127.0.0.1'  https://www.test2.com:9443`

you can make a try in this way.  ^_^

File: api/internal/handler/ssl/ssl.go (hunk 2 above)
Comment (membphis) [reply api/internal/handler/ssl/ssl.go:150]: and I think we'd better add some comment here, it should be useful for code reader

Comment (nic-chen) [reply api/internal/handler/ssl/ssl.go:150]: OK.

File: .github/workflows/e2e-test-backend.yml (hunk 3 above)
Comment (nic-chen) [reply .github/workflows/e2e-test-backend.yml:33]: thanks. I will try for it. but it's an example, we are not use curl to test.

Comment (membphis) [reply .github/workflows/e2e-test-backend.yml:33]: ok, got it. we can write some comment first, then we can fix it in a better way.

Comment (nic-chen) [reply .github/workflows/e2e-test-backend.yml]: It works!

File: api/internal/handler/ssl/ssl.go [hunk 5]
```diff
@@ -34,6 +34,7 @@ import (
 	"github.com/shiningrush/droplet/wrapper"
 	wgin "github.com/shiningrush/droplet/wrapper/gin"
 
+	"github.com/apisix/manager-api/conf"
```
Comment (membphis) [inline api/internal/handler/ssl/ssl.go:37]: we'll move this module to another place, is it right?

File: api/internal/handler/ssl/ssl.go [hunk 6]
```diff
@@ -147,6 +148,8 @@ func (h *Handler) Create(c droplet.Context) (interface{}, error) {
 	}
 
 	ssl.ID = input.ID
+	//set default value for SSL status, if not set, it will be 0 which means disable.
+	ssl.Status = conf.SSLDefaultStatus
 	if err := h.sslStore.Create(c.Context(), ssl); err != nil {
 		return handler.SpecCodeResponse(err), err
```
Comment (membphis) [inline api/internal/handler/ssl/ssl.go:154]: Did we catch this error and write it to the error log?  please confirm it. if not, we can create a new issue to fix it

File: api/internal/handler/ssl/ssl.go [hunk 7]
```diff
@@ -169,6 +172,9 @@ func (h *Handler) Update(c droplet.Context) (interface{}, error) {
 	if input.ID != "" {
 		ssl.ID = input.ID
 	}
+
+	//set default value for SSL status, if not set, it will be 0 which means disable.
+	ssl.Status = conf.SSLDefaultStatus
 	if err := h.sslStore.Update(c.Context(), ssl, true); err != nil {
 		return handler.SpecCodeResponse(err), err
```
Comment (membphis) [inline api/internal/handler/ssl/ssl.go:179]: ditto

File: api/test/e2e/ssl_test.go [hunk 8]
```diff
@@ -0,0 +1,138 @@
...
+
+	for _, tc := range tests {
+		testCaseCheck(tc)
+	}
+
+	//try again after deleting SSL, make a HTTPS request
+	time.Sleep(time.Duration(20) * time.Millisecond)
+	_, err = http.Get("https://www.test2.com:9443")
+	assert.NotNil(t, err)
+	assert.EqualError(t, err, "Get https://www.test2.com:9443: remote error: tls: internal error")
```
Comment (moonming) [inline api/test/e2e/ssl_test.go:137]: why return ssl error? The router has been deleted

File: api/internal/handler/ssl/ssl.go (hunk 5 above)
Comment (nic-chen) [reply api/internal/handler/ssl/ssl.go:37]: yes. when we adjust the code dir.

File: api/internal/handler/ssl/ssl.go (hunk 6 above)
Comment (nic-chen) [reply api/internal/handler/ssl/ssl.go:154]: sure, I will create an issue.

File: api/test/e2e/ssl_test.go (hunk 8 above)
Comment (nic-chen) [reply api/test/e2e/ssl_test.go:137]: because APISIX exit when no SSL match:
https://github.com/apache/apisix/blob/master/apisix/init.lua#L174-L180

Comment (moonming) [reply api/test/e2e/ssl_test.go:137]: Then why you need to delete router?https://github.com/apache/apisix-dashboard/pull/719/files#diff-c2b7edfd95881ffeb7a02870b56d8c228b7b1f0f83d78be56f4462091bf76dc7R112-R117
 just delete ssl is enough

Comment (nic-chen) [reply api/test/e2e/ssl_test.go:137]: just clean test data.

Comment (moonming) [reply api/test/e2e/ssl_test.go:137]: Please move delete router to the end, and add comments

Comment (nic-chen) [reply api/test/e2e/ssl_test.go:133]: updated.

File: api/conf/conf.go [hunk 9]
```diff
@@ -40,16 +40,17 @@ const (
...
+	Schema           gjson.Result
+	WorkDir          = "."
+	ServerHost       = "127.0.0.1"
+	ServerPort       = 80
+	ETCDEndpoints    = []string{"127.0.0.1:2379"}
+	ErrorLogLevel    = "warn"
+	ErrorLogPath     = "logs/error.log"
+	UserList         = make(map[string]User, 2)
+	AuthConf         Authentication
+	SSLDefaultStatus = 1 //enable ssl by default
```
Comment (membphis) [inline api/conf/conf.go:53]: `CONST` variable? avoid magic number

File: api/internal/handler/ssl/ssl.go (hunk 6 above)
Comment (membphis) [reply api/internal/handler/ssl/ssl.go:154]: if you created, you should better leave an issue id here.

**Review by membphis — APPROVED** [review]
LGTM, except the minor issues that I have written.

**Review by gxthrj — APPROVED** [review]

**Review by moonming — APPROVED** [review]

File: api/conf/conf.go (hunk 9 above)
Comment (membphis) [reply api/conf/conf.go:53]: @nic-chen please create a new issue about this point, we will fix this later
