### PR TITLE
fix: delete POST method in /apisix/admin/consumer

### LINKED ISSUE #852: bug: manager-api supported `POST` method for consumer
# Bug report

## Describe the bug
manager-api supported `POST` method for consumer.
but it should not support the `POST` method for consumer, the same as APISIX's adminapi.
```testcase
{
			caseDesc: "create consumers with post method",
			Object:   MangerApiExpect(t),
			Path:     "/apisix/admin/consumers",
			Method:   http.MethodPost,
			Body: `{
				"username":"case_9",
				"desc": "new consumer",
				"create_time": 1602883670,
				"update_time": 1602893670
		   }`,
			Headers:      map[string]string{"Authorization": token},
			ExpectStatus: http.StatusMethodNotAllowed,
		},
```

### PR DESCRIPTION
**Pull request by starsz**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

fix #852

### CODE REVIEW

File: api/test/e2e/consumer_test.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+
+func TestConsumer_Create_And_Get(t *testing.T) {
+	tests := []HttpTestCase{
+		{
+			caseDesc: "create consumer by POST",
+			Object:   MangerApiExpect(t),
+			Path:     "/apisix/admin/consumers",
+			Method:   http.MethodPost,
+			Body: `{
+              "username": "consumer_1",
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:32]: bad indentation

File: api/test/e2e/consumer_test.go [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+
+func TestConsumer_Update_And_Get(t *testing.T) {
+	tests := []HttpTestCase{
+		{
+			caseDesc: "update consumer by PUT",
+			Object:   MangerApiExpect(t),
+			Path:     "/apisix/admin/consumers/consumer_2",
+			Method:   http.MethodPut,
+			Body: `{
+              "username": "consumer_2",
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:110]: ditto

**Review by membphis — APPROVED** [review]
LGTM, except minor code style.

@nic-chen @gxthrj please take a look at this PR

File: api/test/e2e/consumer_test.go [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+
+import (
+	"net/http"
+	"testing"
+)
+
+func TestConsumer_Create_And_Get(t *testing.T) {
+	tests := []HttpTestCase{
+		{
+			caseDesc: "create consumer by POST",
```
Comment (nic-chen) [inline api/test/e2e/consumer_test.go:27]: Need to test to get consumer first to ensure that the consumer has not been created before

File: api/test/e2e/consumer_test.go [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+			ExpectStatus: http.StatusNotFound,
+			ExpectBody:   "404 page not found",
+		},
+		{
+			caseDesc: "create consumer by PUT",
+			Object:   MangerApiExpect(t),
+			Path:     "/apisix/admin/consumers",
+			Method:   http.MethodPut,
+			Body: `{
+              "username": "consumer_2",
```
Comment (nic-chen) [inline api/test/e2e/consumer_test.go:53]: bad indentation

File: api/test/e2e/consumer_test.go [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+		},
+		{
+			caseDesc:     "get consumer",
+			Object:       MangerApiExpect(t),
+			Path:         "/apisix/admin/consumers/consumer_2",
+			Method:       http.MethodGet,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
+			ExpectBody:   "\"rejected_code\":504",
+		},
```
Comment (nic-chen) [inline api/test/e2e/consumer_test.go:132]: Need to delete consumers just created.

File: api/test/e2e/consumer_test.go (hunk 3 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go:43]: OK, Fixed.

File: api/test/e2e/consumer_test.go (hunk 5 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go:148]: OK. Deleted

File: api/test/e2e/consumer_test.go (hunk 1 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Fixed.

File: api/test/e2e/consumer_test.go (hunk 2 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: OK. Fixed

File: api/test/e2e/consumer_test.go (hunk 4 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: OK fixed.

**Comment by nic-chen** [comment]
CI failed. please have a look. thanks.

**Comment by idbeta** [comment]
@starsz Can the E2E use case file use another name?  because `consumer_test.go` is used by #830 ...

**Comment by starsz** [comment]
> @starsz Can the E2E case file use another name? because `consumer_test.go` is used by #830 ...

I don't think it's a problem. Next PR can rebase the master branch if my PR is merged first.

**Comment by starsz** [comment]
> CI failed. please have a look. thanks.

OK. CI had passed.

File: api/test/e2e/consumer_test.go [hunk 6]
```diff
@@ -0,0 +1,202 @@
...
+					"time_window": 60,
+					"rejected_code": 503,
+					"key": "remote_addr"
+					}
+				},
+				"desc": "test description"
+			}`,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusBadRequest,
+			ExpectBody:   "",
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:115]: useless?

File: api/test/e2e/consumer_test.go [hunk 7]
```diff
@@ -0,0 +1,202 @@
...
+func TestConsumer_Create_And_Get(t *testing.T) {
+	tests := []HttpTestCase{
+		{
+			caseDesc:     "check consumer is not exist",
+			Object:       MangerApiExpect(t),
+			Path:         "/apisix/admin/consumers/consumer_1",
+			Method:       http.MethodGet,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusNotFound,
+			ExpectBody:   "",
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:34]: useless ?

File: api/test/e2e/consumer_test.go [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+		},
+		{
+			caseDesc:     "check consumer is not exist",
+			Object:       MangerApiExpect(t),
+			Path:         "/apisix/admin/consumers/consumer_2",
+			Method:       http.MethodGet,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusNotFound,
+			ExpectBody:   "",
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:43]: ditto

File: api/test/e2e/consumer_test.go [hunk 9]
```diff
@@ -0,0 +1,202 @@
...
+					"rejected_code": 503,
+					"key": "remote_addr"
+					}
+				},
+				"desc": "test description"
+			}`,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
+			ExpectBody:   "",
+			Sleep:        2 * time.Second,
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:155]: i  think 100~200ms should be enough

File: api/test/e2e/consumer_test.go [hunk 10]
```diff
@@ -0,0 +1,202 @@
...
+					"rejected_code": 504,
+					"key": "remote_addr"
+					}
+				},
+				"desc": "test description"
+			}`,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
+			ExpectBody:   "",
+			Sleep:        2 * time.Second,
```
Comment (membphis) [inline api/test/e2e/consumer_test.go:177]: ditto

**Review by membphis — CHANGES_REQUESTED** [review]

**Review by gxthrj — APPROVED** [review]
LGTM

File: api/test/e2e/consumer_test.go (hunk 9 above)
Comment (nic-chen) [reply api/test/e2e/consumer_test.go:155]: we could use the same 'sleepTime'

File: api/test/e2e/consumer_test.go [hunk 11]
```diff
@@ -0,0 +1,202 @@
...
+			ExpectStatus: http.StatusBadRequest,
+			ExpectBody:   "",
+		},
+		{
+			caseDesc:     "delete consumer",
+			Object:       MangerApiExpect(t),
+			Path:         "/apisix/admin/consumers/consumer_2",
+			Method:       http.MethodDelete,
+			Headers:      map[string]string{"Authorization": token},
+			ExpectStatus: http.StatusOK,
```
Comment (moonming) [inline api/test/e2e/consumer_test.go:123]: How to check the delete is successful?

Comment (moonming) [reply api/test/e2e/consumer_test.go:123]: The response code is not enough, we need to check in data plane

File: api/test/e2e/consumer_test.go [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+			ExpectBody:   "\"rejected_code\":504",
+		},
+		{
+			caseDesc:     "delete consumer",
+			Object:       MangerApiExpect(t),
+			Path:         "/apisix/admin/consumers/consumer_3",
+			Method:       http.MethodDelete,
+			Headers:      map[string]string{"Authorization": token},
```
Comment (moonming) [inline api/test/e2e/consumer_test.go:193]: Ditto

**Review by moonming — CHANGES_REQUESTED** [review]

**Comment by idbeta** [comment]
> > @starsz Can the E2E case file use another name? because `consumer_test.go` is used by #830 ...
> 
> Hi, I don't think it's a problem. Next PR can rebase the master branch if my PR is merged first.

got it.

File: api/test/e2e/consumer_test.go (hunk 9 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go:155]: @nic-chen Hi, Why we should use the same `sleepTime`, In my opinion, only create and update consumer need to sleep for a while.

File: api/test/e2e/consumer_test.go (hunk 11 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go:123]: OK, Fixed.

File: api/test/e2e/consumer_test.go (hunk 12 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go:193]: OK, Fixed.

File: api/test/e2e/consumer_test.go (hunk 7 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Fixed.

File: api/test/e2e/consumer_test.go (hunk 8 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Fixed.

File: api/test/e2e/consumer_test.go (hunk 10 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Fixed.

File: api/test/e2e/consumer_test.go (hunk 6 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Fixed.

File: api/test/e2e/consumer_test.go (hunk 9 above)
Comment (starsz) [reply api/test/e2e/consumer_test.go]: Hi, @membphis, When I reduce the sleep time, It will cause CI to fail.
So I think maybe it's not enough.

File: api/internal/handler/consumer/consumer.go [hunk 13]
```diff
@@ -97,35 +95,13 @@ func (h *Handler) List(c droplet.Context) (interface{}, error) {
...
-		return handler.SpecCodeResponse(err), err
-	}
-
-	return nil, nil
-}
-
-type UpdateInput struct {
+type SetInput struct {
 	Username string `auto_read:"username,path"`
 	entity.Consumer
```
Comment (tokers) [inline api/internal/handler/consumer/consumer.go:100]: Embed members should be put at the top.

File: api/test/e2e/base.go [hunk 14]
```diff
@@ -32,6 +33,11 @@ import (
 
 var token string
 
+var MExpect *httpexpect.Expect
```
Comment (tokers) [inline api/test/e2e/base.go:36]: Use var (
......
)

File: api/internal/handler/consumer/consumer.go (hunk 13 above)
Comment (starsz) [reply api/internal/handler/consumer/consumer.go:100]: Good style.Fiexd.

**Review by nic-chen — APPROVED** [review]

File: api/test/e2e/base.go (hunk 14 above)
Comment (starsz) [reply api/test/e2e/base.go]: Deleted those codes.

**Comment by starsz** [comment]
Hi. Ping @membphis @moonming. Please have a look.

**Review by moonming — APPROVED** [review]

**Comment by ShiningRush** [comment]
I think it would be better to merge after #859 merged, we could not maintain handler's integration test cases anymore.

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
> I think it would be better to merge after #859 merged, we could not maintain handler's integration test cases anymore.

@ShiningRush I think we can merge this PR and #859 now. what do you think?
