### PR TITLE
fix: delete null value in request body

### LINKED ISSUE #2019: [health_check] validate form item "checks.active.port"
## Issue description
upstream 节点健康检查在不配置 active.port 的时候，校验出错

QV JGL)P 6NBXR3ZNGETC3

## Expected behavior
官网介绍：
active.port: 用于发现 upstream 节点健康可用的自定义主机端口（可选），配置此项会覆盖 upstream 节点中的端口。

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

In the optional `InputNumber` component of the entire project, when the user chooses not to fill in, the value of the field in the request body is `null`, which will cause a request error.

The correct approach is to delete all fields with `null` values in the request body.

**Related issues**

fix #2019 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: web/src/app.tsx [hunk 1]
```diff
@@ -55,13 +56,27 @@ export const layout = ({ initialState }: { initialState: { settings?: LayoutSett
   };
 };
 
+/* eslint no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ["obj"] }] */
+const nullValueFilter = (obj: Record<string, any>) => {
+  Object.keys(obj).forEach((key) => {
+    if (isPlainObject(obj[key])) {
+      nullValueFilter(obj[key]);
+    } else if (obj[key] === null) {
```
Comment (juzhiyuan) [inline web/src/app.tsx:64]:
```suggestion
    } else if ([null, undefined].includes(obj[key])) {
```

File: web/src/app.tsx [hunk 2]
```diff
@@ -55,13 +56,27 @@ export const layout = ({ initialState }: { initialState: { settings?: LayoutSett
   };
 };
 
+/* eslint no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ["obj"] }] */
+const nullValueFilter = (obj: Record<string, any>) => {
+  Object.keys(obj).forEach((key) => {
+    if (isPlainObject(obj[key])) {
```
Comment (juzhiyuan) [inline web/src/app.tsx:62]: `obj[key]` === `Object.entries(xxx)`

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Comment by liuxiran** [comment]
merged, thanks a lot
