### PR TITLE
fix: nodes format not works

### LINKED ISSUE #783: 上游节点分组节点主机权重配置为0时，dashboard进行路由配置时，选后节点分组，报undefined
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [ ] Bug

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
api-dashboard : 2.0 rc3
OS:centos7

1、上游节点分组节点主机权重配置为0时，dashboard进行路由配置时，选后节点分组，报undefined;
etcd里数据是0
image

### LINKED ISSUE #786: bug: when created route by adminAPI, "upstream" can not be modified by dashboard
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other
__
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX master + dashabord 2.0 rc3

1. create a route with adminAPI
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
 {
     "name":"test_route",
     "methods":["GET","POST"],
     "uri": "/name",
     "upstream": {
         "type": "roundrobin",
         "nodes": {
             "127.0.0.1:9797": 1
         }
     }
}'
```
2."upstream"(127.0.0.1:9797) cannot be displayed and modified( or added ) by the dashboard
image

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

close #786
close #783

two issues are caused by nodes format

### CODE REVIEW

**Review by spacewander — APPROVED** [review]

File: api/internal/core/entity/format.go [hunk 1]
```diff
@@ -17,26 +17,30 @@
...
 			if len(strArr) != 2 {
-				log.Println("length of string array is not 2")
+				log.Warn("length of string array is not 2")
 				return obj
 			}
 
 			port, err := strconv.Atoi(strArr[1])
 			if err != nil {
-				log.Println("parse int fail:", err)
+				log.Errorf("parse int fail:", err)
```
Comment (tokers) [inline api/internal/core/entity/format.go:43]: Missing format prompt like `%v` or `%s`, the `%s` is preferred since we don't want to see the dynamic type of error, we only need the literal string. This lint error can be detected by golangci-lint.

File: api/internal/core/entity/format.go [hunk 2]
```diff
@@ -17,26 +17,30 @@
...
 	var nodes []*Node
-	if value, ok := obj.(map[string]float64); ok {
+	switch objType := obj.(type) {
+	case map[string]float64:
+		log.Infof("nodes type: %v", objType)
 		var strArr []string
+		value := obj.(map[string]float64)
 		for key, val := range value {
 			node := &Node{}
 			strArr = strings.Split(key, ":")
```
Comment (tokers) [inline api/internal/core/entity/format.go:35]: The key splitting logic can be replaced by using `net.SplitHostPort`, we may encapsulate it with port validation and IP/domain check.

File: api/internal/core/entity/format.go [hunk 3]
```diff
@@ -46,13 +50,35 @@ func NodesFormat(obj interface{}) interface{} {
 			nodes = append(nodes, node)
```
Comment (tokers) [inline api/internal/core/entity/format.go:50]: What about using structure literal initialization:

```go
node := &Node{
    Host: strArr[0].
    Port: port,
    Weight: int(val)
}
```

File: api/internal/core/entity/format.go [hunk 4]
```diff
@@ -46,13 +50,35 @@ func NodesFormat(obj interface{}) interface{} {
...
 		}
 		return nodes
-	}
+	case map[string]interface{}:
+		log.Infof("nodes type: %v", objType)
+		var strArr []string
+		value := obj.(map[string]interface{})
+		for key, val := range value {
+			node := &Node{}
+			strArr = strings.Split(key, ":")
```
Comment (tokers) [inline api/internal/core/entity/format.go:59]: Key splitting can be extracted as a function, it's used multiple times.

File: api/internal/core/entity/format.go [hunk 5]
```diff
@@ -46,13 +50,35 @@ func NodesFormat(obj interface{}) interface{} {
...
+			port, err := strconv.Atoi(strArr[1])
+			if err != nil {
+				log.Errorf("parse int fail:", err)
+				return obj
+			}
 
-	if list, ok := obj.([]interface{}); ok {
+			node.Host = strArr[0]
+			node.Port = port
+			node.Weight = int(val.(float64))
```
Comment (tokers) [inline api/internal/core/entity/format.go:73]: Ditto (literal structure initialization)

File: api/internal/core/entity/format_test.go [hunk 6]
```diff
@@ -23,19 +23,62 @@ import (
...
+	// nodes format
+	nodes := NodesFormat(route.Upstream.Nodes)
 
-	assert.Equal(t, 1, len(nodes))
-	assert.Equal(t, "127.0.0.1", nodes[0].Host)
-	assert.Equal(t, 8080, nodes[0].Port)
-	assert.Equal(t, 1, nodes[0].Weight)
+	// json encode for client
+	res, err := json.Marshal(nodes)
+	assert.Nil(t,err)
```
Comment (tokers) [inline api/internal/core/entity/format_test.go:50]: Style: need a space after `,`.

File: api/internal/core/entity/format_test.go [hunk 7]
```diff
@@ -23,19 +23,62 @@ import (
...
+	routeStr := `{
+        "uris": ["/*"],
+        "upstream": {
+            "type": "roundrobin",
+            "nodes": {"127.0.0.1:8080": 0}
+        }
+    }`
+
+	// bind struct
+	var  route Route
```
Comment (tokers) [inline api/internal/core/entity/format_test.go:68]: Redundant spaces after `var`.

File: api/internal/core/entity/format_test.go [hunk 8]
```diff
@@ -23,19 +23,62 @@ import (
...
+	nodes := NodesFormat(route.Upstream.Nodes)
+
+	// json encode for client
+	res, err := json.Marshal(nodes)
+	assert.Nil(t,err)
+	jsonStr := string(res)
+	assert.Contains(t, jsonStr, `"weight":0`)
+	assert.Contains(t, jsonStr, `"port":8080`)
+	assert.Contains(t, jsonStr, `"host":"127.0.0.1"`)
+
```
Comment (tokers) [inline api/internal/core/entity/format_test.go:82]: Redundant empty line.

File: api/internal/core/entity/format.go (hunk 1 above)
Comment (nic-chen) [reply api/internal/core/entity/format.go]: fixed.

File: api/internal/core/entity/format.go (hunk 2 above)
Comment (nic-chen) [reply api/internal/core/entity/format.go]: updated.

File: api/internal/core/entity/format.go (hunk 3 above)
Comment (nic-chen) [reply api/internal/core/entity/format.go:59]: updated.

File: api/internal/core/entity/format.go (hunk 4 above)
Comment (nic-chen) [reply api/internal/core/entity/format.go]: updated.

File: api/internal/core/entity/format.go (hunk 5 above)
Comment (nic-chen) [reply api/internal/core/entity/format.go]: updated.

File: api/internal/core/entity/format_test.go (hunk 6 above)
Comment (nic-chen) [reply api/internal/core/entity/format_test.go]: fixed

File: api/internal/core/entity/format_test.go (hunk 7 above)
Comment (nic-chen) [reply api/internal/core/entity/format_test.go]: fixed

File: api/internal/core/entity/format_test.go (hunk 8 above)
Comment (nic-chen) [reply api/internal/core/entity/format_test.go]: fixed

File: api/internal/core/entity/format_test.go [hunk 9]
```diff
@@ -23,19 +23,60 @@ import (
...
+        "uris": ["/*"],
+        "upstream": {
+            "type": "roundrobin",
+            "nodes": [{
+                "host": "127.0.0.1",
+                "port": 80,
+                "weight": 0
+            }]
+        }
+    }`
```
Comment (membphis) [inline api/internal/core/entity/format_test.go:38]: bad indentation

File: api/internal/core/entity/format.go [hunk 10]
```diff
@@ -17,51 +17,73 @@
...
 import (
-	"log"
+	"net"
 	"strconv"
-	"strings"
+
+	"github.com/apisix/manager-api/log"
 )
 
+func MapKV2Node(key string, val float64) (*Node, error) {
```
Comment (tokers) [inline api/internal/core/entity/format.go:26]: Maybe in small camel case?

Comment (nic-chen) [reply api/internal/core/entity/format.go]: updated.

File: api/internal/core/entity/format_test.go (hunk 9 above)
Comment (nic-chen) [reply api/internal/core/entity/format_test.go]: fixed.

**Review by tokers — APPROVED** [review]
