### PR TITLE
fix: support edit and show vars

### LINKED ISSUE #3145: bug: route vars cannot be displayed or edited using new admin ui / dashboard
### Current Behavior

Tried to put admin ui behind sso by using regular expression to match route. As far as I understand, i need to create a route for root with vars matching the apisix admin ui and admin api paths.

Minimal example that create the bug:
route: `{ "uri": "/*", "vars": [  [  "uri",  "~~",  "^/(ui|apisix).*$" ] ] }`

I was not able to modify or create a new route that would accept the vars using the new dashboard / admin ui. So, i turned to the admin api and created a new route.

Now, trying to view the route in the new admin ui / dashboard ui, i receive a javascript error: a.trim is not a function
Seems like handling vars, atleast with medium complexity, is not working either way with the admin ui. Neither creating or viewing seems to work.

Seems like you guys are handling this field in the ui completely wrong :( The rest of the new ui is working much better than the old sone though. Great job!

### Expected Behavior

Able to create, edit and view routes with vars.

### Error Logs

_No response_

### Steps to Reproduce

1. Try to input any vars into a route: Route is not able to be submitted.

1. Try to open a route with any vars: The route cannot be opened due to client side javascript error. Trying to call string method on an array.

### Environment

- APISIX version (run `apisix version`): 3.13

### PR DESCRIPTION
**Pull request by SkyeYoung**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Support editing and echoing vars

Because it needs to be used in the form, the error reporting logic of the Editor has been primarily adjusted, and the styles have been adapted.

|Edit|Disabled, View|
|-|-|
|CleanShot 2025-07-25 at 16 04 40@2x|image| 

```POST
curl 'http://localhost:5173/apisix/admin/routes' \
  -H 'Content-Type: application/json' \
  -H 'X-API-KEY: xxx' \
  --data-raw '{"uri":"/*","vars":[["uri","~~","^/(ui|apisix).*$"]],"upstream":{"nodes":[{"host":"test","port":1,"weight":0,"priority":0}]}}'
```

**Related issues**

fix #3145

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: src/components/form-slice/FormItemPlugins/PluginEditorDrawer.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ export type PluginEditorDrawerProps = Pick<PluginCardListProps, 'mode'> & {
 };
 
 const toConfigStr = (p: object): string => {
-  return !isEmpty(p) ? JSON.stringify(p, null, 2) : '{}';
+  return !isEmpty(p) && !isNil(p) ? JSON.stringify(p, null, 2) : '{}';
```
Comment (SkyeYoung) [inline src/components/form-slice/FormItemPlugins/PluginEditorDrawer.tsx:38]: !isEmpty will ignore `undefined`

File: src/components/form/Editor.tsx [hunk 2]
```diff
@@ -73,67 +73,63 @@ export const FormItemEditor = <T extends FieldValues>(
   const { t } = useTranslation();
   const { controllerProps, restProps } = genControllerProps(props, '');
   const { customSchema, language, isLoading, ...wrapperProps } = restProps;
-  const { setError, clearErrors } = useFormContext<{
-    [name: string]: object;
-  }>();
-  const customErrorField = `${props.name}-editor`;
-  const { errors } = useFormState({ name: customErrorField });
+  const { trigger } = useFormContext();
+  const monacoErrorRef = useRef<string | null>(null);
```
Comment (SkyeYoung) [inline src/components/form/Editor.tsx:77]: The original method was to directly use `setError` and `clearError`, which would trigger a global update of the form with every input. Also, due to the various dependencies on state, it might update multiple times.

Now, using `ref` allows React and RHF to ignore state updates, and only when `onValidate` is triggered, actively call `trigger`, which enables RHF to obtain an error (ref) once through internal validation logic. This significantly reduces the dependencies on state and limits error updates within the component.

**Comment by Baoyuantop** [comment]
Hi @x-etienne, we are releasing version 3.14.1 which will include these changes.
