### PR TITLE
fix: preserve plugins with empty config using targeted approach

### LINKED ISSUE #3269: Plugin with empty json config is dropped when add or edit Route
### Issue description

if you add a plugin with empty config when add or edit route, the plugin is not saved.

### Expected behavior

key-auth plugin saved

### How to Reproduce

1. add/edit route
2. add a key-auth plugin with empty config
3. save
4. view route
5. the key-auth plugin is not saved.

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

_No response_

### LINKED ISSUE #3270: Discovery Args are droped  when edit upstream
### Issue description

when add or edit upstream，Discovery Args are droped without sending to server
Image

### Expected behavior

Discovery Args send and saved

### How to Reproduce

1. add any upstream
2. set Service Discovery info
3. save
Image

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`): 3.14.1
- OS (cmd: `uname -a`): 3.10.0-693.21.1.std7a.el7.0.x86_64 #1 SMP Mon Apr 9 01:47:10 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
nginx version: openresty/1.27.1.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 3.5.4 30 Sep 2025
TLS SNI support enabled
configure arguments: --prefix=/home/work/app/apisix_preview/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I /home/work/app/apisix_preview/openresty/pcre/include -I /home/work/app/apisix_preview/openresty/openssl/include -I /home/work/app/apisix_preview/openresty/zlib/include' --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.28 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.16 --with-ld-opt='-Wl,-rpath,/home/work/app/apisix_preview/openresty/luajit/lib -L/home/work/app/apisix_preview/openresty/pcre/lib -L/home/work/app/apisix_preview/openresty/openssl/lib -L/home/work/app/apisix_preview/openresty/zlib/lib -Wl,-rpath,/home/work/app/apisix_preview/openresty/pcre/lib:/home/work/app/apisix_preview/openresty/openssl/lib:/home/work/app/apisix_preview/openresty/zlib/lib' --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-file-aio --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-http_v3_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_slice_module --with-threads --with-compat --with-pcre-jit --with-http_ssl_module --with-cc='ccache gcc -fdiagnostics-color=always' --add-module=/tmp/src/build_space/tengine-3.1.0/modules/ngx_debug_conn --add-module=/tmp/src/build_space/tengine-3.1.0/modules/ngx_debug_timer --add-module=/tmp/src/build_space/tengine-3.1.0/modules/ngx_slab_stat --add-module=/tmp/src/ngx_multi_upstream_module-1.3.2 --add-module=/tmp/src/apisix-nginx-module-1.19.3 --add-module=/tmp/src/apisix-nginx-module-1.19.3/src/stream --add-module=/tmp/src/apisix-nginx-module-1.19.3/src/meta --add-module=/tmp/src/lua-var-nginx-module-v0.5.3 --add-module=/tmp/src/lua-resty-events-0.2.0 --with-stream
- etcd version, if have (cmd: run `etcd --version`):3.4.14	
- apisix-dashboard version, if have: 39be363cdbc5395d3163572c532be95f3dbad03a
- Browser version, if have:  Microsoft Edge 版本 142.0.3595.94 (正式版本) (64 位)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DSingh0304**
**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Fields with empty object values (`{}`) were being silently dropped when saving. This affects:
- **Plugins** that don't require configuration (e.g., `key-auth`, `prometheus`, `echo`)
- **Upstream `discovery_args`** when using Service Discovery

**Root Cause:** The `fast-clean` library used in [src/utils/producer.ts](cci:7://file:///home/deep/Desktop/Code/Organizations/apisix-dashboard/src/utils/producer.ts:0:0-0:0) has `emptyObjectsCleaner: true` by default, which removes empty objects before sending data to the server.

**Fix:** Set `emptyObjectsCleaner: false` in the [deepCleanEmptyKeys](cci:1://file:///home/deep/Desktop/Code/Organizations/apisix-dashboard/src/utils/producer.ts:22:0-31:5) function to preserve empty objects.

**Related issues**

fix #3269 
fix #3270

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: src/utils/producer.ts
Comment (SkyeYoung) [inline src/utils/producer.ts:1]: Hi, pls add a test for this case.

Comment (DSingh0304) [reply src/utils/producer.ts:1]: Yes i will add the test in some time.

Comment (DSingh0304) [reply src/utils/producer.ts:1]: Hey I have added the test...

Comment (SkyeYoung) [reply src/utils/producer.ts:1]: sorry for too late.

File: e2e/tests/routes.empty-plugin-config.spec.ts [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+        uri: routeUri,
+        plugins: {
+            'key-auth': {},
+        },
+        upstream: {
+            nodes: [{ host: 'httpbin.org', port: 80, weight: 1 }],
+            type: 'roundrobin',
+        },
+    });
+
```
Comment (Baoyuantop) [inline e2e/tests/routes.empty-plugin-config.spec.ts]: I believe this is also part of the testing path and should be created within the testing process rather than through the API.

**Review by Baoyuantop — COMMENTED** [review]
The PR description also mentions fixing https://github.com/apache/apisix-dashboard/issues/3270

We also need to write tests to verify this issue.

File: e2e/tests/routes.empty-plugin-config.spec.ts (hunk 1 above)
Comment (DSingh0304) [reply e2e/tests/routes.empty-plugin-config.spec.ts]: Oh okay I ll look into it..

Comment (DSingh0304) [reply e2e/tests/routes.empty-plugin-config.spec.ts]: @Baoyuantop I have made the changes...

**Review by SkyeYoung — APPROVED** [review]

**Review by Baoyuantop — COMMENTED** [review]
It is recommended to modify the calling parameters of the deepCleanEmptyKeys function, rather than adding complex marking logic to the pipeline.

```
export const produceDeepCleanEmptyKeys = (opts: ICleanerOptions = {}) =>
  produce((draft) => {
    deepCleanEmptyKeys(draft, {
      emptyObjectsCleaner: false,  // Key change: Do not clean up empty objects.
      ...opts,
    });
  });
```

File: e2e/tests/upstreams.empty-discovery-args.spec.ts [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+ * does not cause the discovery_args field to be dropped.
+ * Regression test for: https://github.com/apache/apisix-dashboard/issues/3270
+ */
+const upstream: APISIXType['Upstream'] = {
+    id: 'upstream_discovery_test',
+    name: 'upstream_discovery_test',
+    desc: 'Upstream with service discovery',
+    discovery_type: 'nacos',
+    service_name: 'test-service',
+    discovery_args: {},
```
[the remark this answers is not in the document]
Comment (DSingh0304) [reply e2e/tests/upstreams.empty-discovery-args.spec.ts]: fixed

File: e2e/tests/upstreams.empty-discovery-args.spec.ts [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+};
+
+test.beforeAll(async () => {
+    await deleteAllUpstreams(e2eReq);
+    await putUpstreamReq(e2eReq, upstream);
+});
+
```
[the remark this answers is not in the document]
Comment (DSingh0304) [reply e2e/tests/upstreams.empty-discovery-args.spec.ts:45]: fixed

File: e2e/tests/upstreams.empty-discovery-args.spec.ts [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+};
+
+test.beforeAll(async () => {
+  await deleteAllUpstreams(e2eReq);
+  await putUpstreamReq(e2eReq, upstream);
+});
+
+test.afterAll(async () => {
+  await deleteAllUpstreams(e2eReq);
+});
```
[the remark this answers is not in the document]
Comment (DSingh0304) [reply e2e/tests/upstreams.empty-discovery-args.spec.ts:48]: Fixed in [4193fe7](https://github.com/apache/apisix-dashboard/pull/3277/commits/4193fe7a1634770c4a3360308035e2f099204348)

**Review by Baoyuantop — CHANGES_REQUESTED** [review]
The core fix (`emptyObjectsCleaner: false`) is correct and the simplest approach — much better than the previous marker-based pipeline. However there are a few issues that should be addressed before merging.

---

### `JSON.stringify` + manual Content-Type in `src/apis/upstreams.ts` — should be reverted

Axios already serializes JS objects to JSON and sets `Content-Type: application/json` by default. Manually calling `JSON.stringify(data)` before passing to Axios means the data is sent as a **pre-stringified string**, which can cause double-encoding issues in certain interceptor scenarios.

No other API file in this project (`routes.ts`, `services.ts`, `consumers.ts`, `ssls.ts`, etc.) uses `JSON.stringify` — they all pass plain objects. This change breaks consistency and is **not needed** for the fix: the empty-object stripping happens in `pipeProduce` on the client side, not during Axios serialization.

**Suggestion:** Revert all changes to `src/apis/upstreams.ts`.

---

### `src/routes/services/add.tsx` — data cleaning logic was moved to an inconsistent location

On master, `pipeProduce(produceRmUpstreamWhenHas('upstream_id'))` lives inside `mutationFn`. This PR splits it: `mutationFn` now receives raw data, and the cleaning happens in `form.handleSubmit`. This breaks the established pattern where data transformation is centralized inside the mutation.

Compare with `src/routes/services/detail.$id/index.tsx` in this same PR — the detail page correctly keeps cleaning inside `mutationFn`. The add page should be consistent.

The `as ServicePostType` cast also masks potential type mismatches.

**Suggestion:** Keep the master pattern — add `produceRmEmptyUpstreamFields` inside `mutationFn` alongside the existing `produceRmUpstreamWhenHas`:

```typescript
mutationFn: (d: ServicePostType) =>
  postServiceReq(
    req,
    pipeProduce(produceRmUpstreamWhenHas('upstream_id'), produceRmEmptyUpstreamFields)(d)
  ),
```

And keep `form.handleSubmit((d) => postService.mutateAsync(d))` unchanged.

---

### `src/utils/useSearchParams.ts` change is unrelated to this PR

The change types `prev` as `Record<string, unknown>` which discards TanStack Router's inferred search-param type, and `as P & Partial<P>` is a no-op cast (`P & Partial<P>` ≡ `P`).

This is unrelated to the empty-object fix and should be removed from this PR (or addressed in a separate one if there's an actual type error to fix).

**Review by Baoyuantop — COMMENTED** [review]
Thanks for the fix. The root cause analysis and fix direction (disabling `emptyObjectsCleaner` + targeted cleanup for upstream empty shell fields) are correct.

However, there's one blocking item to address:

The reproduction in #3269 covers both **add** and **edit** paths ("add or edit route"). The current e2e only covers the "edit existing config to `{}`" path but misses the "create with empty plugin config `{}`" path. These two paths are not fully equivalent in the frontend serialization pipeline, so the missing test case leaves a regression blind spot.

Please add a minimal e2e test:
- Create a Route with `key-auth` set to `{}`
- After saving, verify in the detail page that `plugins["key-auth"]` still exists with value `{}`

Once this is covered and CI passes, we can re-review.

**Comment by DSingh0304** [comment]
Hi @Baoyuantop all the checks pass can you please review the PR. I will fix the merge conflict.

**Review by Baoyuantop — APPROVED** [review]
