### PR TITLE
fix(be): search by status on the route list page is invalid

### LINKED ISSUE #1189: bug: search by status on the route list page is invalid
# Bug report

## Describe the bug
image
I think the query string is wrong.
```
Request URL: http://127.0.0.1:9000/apisix/admin/routes?label=&page=1&page_size=20
Request Method: GET
```

### PR DESCRIPTION
**Pull request by Jaycean**
Signed-off-by: Jacean <jinchen_jacean@163.com>

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
fix #1189 
___
### Bugfix
- Description
The backend does not judge the status field

- How to fix?
Add status field

### CODE REVIEW

File: api/internal/handler/route/route.go [hunk 1]
```diff
@@ -218,7 +220,11 @@ func (h *Handler) List(c droplet.Context) (interface{}, error) {
 			if input.Label != "" && !utils.LabelContains(obj.(*entity.Route).Labels, labelMap) {
 				return false
 			}
-
+			
+		        status, _ := strconv.Atoi(input.Status)
```
Comment (starsz) [inline api/internal/handler/route/route.go:224]: Hi, I think this can be done before the `List` function. 
And we need to check the error. Return `400` if err is not nil.

File: api/internal/handler/route/route.go [hunk 2]
```diff
@@ -218,7 +220,11 @@ func (h *Handler) List(c droplet.Context) (interface{}, error) {
...
+			if input.Status != "" && uint8(obj.(*entity.Route).Status) != uint8(status) {
```
Comment (starsz) [inline api/internal/handler/route/route.go:225]: There is an easy way.Just compare `strconv.Itoa(int(obj.(*entity.Route).Status))` and status.

Comment (Jaycean) [reply api/internal/handler/route/route.go:225]: Yes, but my biggest problem now is that no matter whether I use uint8 or string for comparison, my test cases can't pass. There's no problem with the function itself. Can you help me take a look at my test cases?  Thks

**Comment by liuxiran** [comment]
This pr can work fine with the https://github.com/apache/apisix-dashboard/pull/1205, but the Unit tests always fail, and logically, we could not find anything wrong.

Please take a look when you are free @nic-chen @tokers @starsz @imjoey , many thanks~~

File: api/internal/handler/route/route.go (hunk 2 above)
Comment (imjoey) [reply api/internal/handler/route/route.go:225]: @Jaycean you can try to `fmt.Sprintf("%d", obj.(*entity.Route).Status)` to compare in string type.

**Comment by starsz** [comment]
> This pr can work fine with the #1205, but the Unit tests always fail, and logically, we could not find anything wrong.
> 
> Please take a look when you are free @nic-chen @tokers @starsz @imjoey , many thanks~~

Hi, I think it was updated by the Update test.

See: 
https://github.com/apache/apisix-dashboard/blob/5a007c759e40854ec6a75ad64178eae9081356ba/api/internal/handler/route/route_test.go#L409-L422

**Comment by nic-chen** [comment]
yes, it has been updated. you should set `status` to 1 in close-in test case.

**Comment by Jaycean** [comment]
@starsz @nic-chen Thank you for your help.

File: api/internal/handler/route/route_test.go [hunk 3]
```diff
@@ -925,6 +927,42 @@ func TestRoute(t *testing.T) {
...
+	err = json.Unmarshal([]byte(reqBody), listInput)
+	assert.Nil(t, err)
+	ctx.SetInput(listInput)
+	retPage, err = handler.List(ctx)
+	assert.Nil(t, err)
+	dataPage = retPage.(*store.ListOutput)
+	assert.Equal(t, len(dataPage.Rows), 1)
+
+        //sleep
+        time.Sleep(time.Duration(100) * time.Millisecond)
```
Comment (starsz) [inline api/internal/handler/route/route_test.go:942]: Style: redundant space.

File: api/internal/handler/route/route.go [hunk 4]
```diff
@@ -219,6 +220,10 @@ func (h *Handler) List(c droplet.Context) (interface{}, error) {
 				return false
 			}
 
+			if input.Status != "" && fmt.Sprintf("%d", obj.(*entity.Route).Status) != input.Status {
```
Comment (starsz) [inline api/internal/handler/route/route.go:223]: I recommend using `strconv.Itoa` instead of `fmt.Sprintf`. Because the former is faster than the latter in the benchmark test.

Comment (Jaycean) [reply api/internal/handler/route/route.go]: Thank you for your suggestion. I'll revise it right away

File: api/internal/handler/route/route_test.go (hunk 3 above)
Comment (starsz) [reply api/internal/handler/route/route_test.go:942]: Hi, @Jaycean don't forget to fix the style problem.

**Comment by juzhiyuan** [comment]
image

CI pending?

**Comment by Jaycean** [comment]
> image
> 
> CI pending?

It should be. I'll run again

File: api/internal/handler/route/route_test.go (hunk 3 above)
Comment (Jaycean) [reply api/internal/handler/route/route_test.go]: done.

**Review by liuxiran — APPROVED** [review]
thanks for all helps, test cases run successfully

**Review by starsz — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by imjoey** [comment]
@Jaycean @juzhiyuan @liuxiran @nic-chen @starsz  Hi, thanks for the great work.

I'm writing here just for your information, I've committed a PR #1224 to backport this bug fix into v2.3 branch for the v2.3 release.

@juzhiyuan shall we also create two new labels?
- `need_backport` to mark a PR that needs backport to other branches
- `backport` to mark a PR is only for backport

Any feedback is welcome. Thanks.
