### PR TITLE
fix(FormItem): Labels

### LINKED ISSUE #3172: labels are missing after SSL creation
### Issue description

**Steps**

1. Commit UI: `70712bd33f55f7979d4cb73a898e9778e0fbfe8b`
2. apache/apisix: `3.13-ubuntu`
3. Navigate to SSL
4. Create a SSL resource
5. Input labels, e.g., `ssl:10`
6. Input other fields and submit
7. Edit the created resource, the labels field is empty
Image

### PR DESCRIPTION
**Pull request by SkyeYoung**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

The original code only updated data when it was first mounted, and the timing of resetting form data was uncertain, which often led to rendering failures.

```ts
// The method of applying API data in the detail/edit page
useEffect(() => {
  if (sslData && !isLoading) {
    form.reset(produceToSSLForm(sslData));
  }
}, [sslData, form, isLoading]);
```

Now, it's directly changed to `useMemo`, and the original `useListState` used for data maintenance has been removed, simplifying data maintenance and ensuring that data can be updated correctly.

For the testing part, it has not yet been decided whether to add unit tests, so I've added ssls check labels tests separately to clarify the testing objectives. This can also help fill a part of #3087 to a certain extent.

**Related issues**

fix/resolve #3172

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: src/components/form-slice/FormSection/index.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ import {
   type TableOfContentsProps,
 } from '@mantine/core';
 import { useShallowEffect } from '@mantine/hooks';
-import clsx from 'clsx';
+import { clsx } from 'clsx';
```
Comment (SkyeYoung) [inline src/components/form-slice/FormSection/index.tsx:25]: fix lint

**Review by Baoyuantop — APPROVED** [review]
