### PR TITLE
fix: enable HTTPS setting unsuccessful in Route

### LINKED ISSUE #688: Enable HTTPS setting unsuccessful in Route
image

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
resolved #688 
___
### Bugfix
- Description
fix: enable HTTPS setting unsuccessful in Route.
- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

File: web/src/pages/Route/transform.ts [hunk 1]
```diff
@@ -133,17 +140,15 @@ export const transformRouteData = (data: RouteModule.Body) => {
...
-      form1Data.redirectOption = 'forceHttps';
-    } else if (redirect?.uri) {
-      form1Data.redirectOption = 'customRedirect';
-      form1Data.ret_code = redirect?.ret_code;
-      form1Data.redirectURI = redirect?.uri;
-    } else {
-      form1Data.redirectOption = 'disabled';
-    }
+  const redirect = data.plugins?.redirect || {};
+  if (redirect?.http_to_https) {
```
Comment (juzhiyuan) [inline web/src/pages/Route/transform.ts:144]: ? Is not needed, because redirect will fallback to empty object.

**Review by juzhiyuan — APPROVED** [review]
