### PR TITLE
fix: make service chash key Input inputable and selectable

### LINKED ISSUE #1952: request help: I have a question about how to edit the key of cookies  in Dashborad 2.2. The old version can edit it directly
### Issue description
I have a question about how to edit the key of cookie in Dashborad 2.2. The old version can edit it directly，
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.2
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.15.8.3
2EE3AE741DD0DA407FA99F64EF67DC05
5668F386C5F8B7C21436DD7E28608E00

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.11  
* apisix-dashboard version, if have: 2.2
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### PR DESCRIPTION
**Pull request by foolwc**
Fixes #1952

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #1952

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by liuxiran** [comment]
@foolwc thanks for your nice work~! The current modification is LGTM, it can support customize the hash key.

And If you can add some test cases, it will help us merge your PR more quickly.

Just refer to https://github.com/apache/apisix-dashboard/blob/0b5196f0b444dac8acb5cf60635806f024de6a0a/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L94, you can try to add case about when choose `hash_on` cookie, you can type `key` a customize one and submit successfully.

And refer to https://github.com/apache/apisix-dashboard/blob/0b5196f0b444dac8acb5cf60635806f024de6a0a/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L134 , you can try to add case about view the above upstream info as expected.

Thanks again, and looking forward to your test cases. If you have any question, please leave message here, we'll help you

File: web/src/components/Upstream/components/Type.tsx [hunk 1]
```diff
@@ -28,6 +28,11 @@ type Props = {
 
 const CHash: React.FC<Pick<Props, 'readonly'>> = ({ readonly }) => {
   const { formatMessage } = useIntl()
+  const [keySearchWord, setKeySearchWord] = useState<string>('');
```
Comment (juzhiyuan) [inline web/src/components/Upstream/components/Type.tsx:31]:
```suggestion
  const [keySearchWord, setKeySearchWord] = useState('');
```

**Comment by foolwc** [comment]
> @foolwc thanks for your nice work~! The current modification is LGTM, it can support customize the hash key.
> 
> And If you can add some test cases, it will help us merge your PR more quickly.
> 
> Just refer to
> 
> https://github.com/apache/apisix-dashboard/blob/0b5196f0b444dac8acb5cf60635806f024de6a0a/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L94
> 
> , you can try to add case about when choose `hash_on` cookie, you can type `key` a customize one and submit successfully.
> And refer to
> 
> https://github.com/apache/apisix-dashboard/blob/0b5196f0b444dac8acb5cf60635806f024de6a0a/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L134
> 
> , you can try to add case about view the above upstream info as expected.
> Thanks again, and looking forward to your test cases. If you have any question, please leave message here, we'll help you

Thanks for your detailed explanation of  writing e2e test.  Please help me review my code again.  Thanks a lot.

File: web/cypress/integration/service/create-service-with-chash-upstream.spec.js [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+    cy.get(selector.notification).should('contain', data.createServiceSuccess);
+  });
+
+  it('should edit the service', function () {
+    cy.visit('/service/list');
+
+    cy.get(selector.nameSearch).type(data.serviceName);
+    cy.contains('Search').click();
+    cy.contains(data.serviceName).siblings().contains('Configure').click();
+    cy.wait(500);
```
Comment (liuxiran) [inline web/cypress/integration/service/create-service-with-chash-upstream.spec.js:85]: Use `cy.wait` is not an good idea, you can try to add assertion  to judge whether the configure page render done

hope this will help
https://github.com/apache/apisix-dashboard/blob/master/web/cypress/integration/route/create-edit-duplicate-delete-route.spec.js#L200

**Comment by liuxiran** [comment]
Thanks for your test cases, it is ok for the whole idea and process👏, and suggestions for improvement I have attached to the review.
To ensure test coverage, we also need test cases for `Route` and `Upstream` module, since actually you update the component. so  looking forward to your other test cases @foolwc thanks again~!

File: web/cypress/integration/service/create-service-with-chash-upstream.spec.js (hunk 2 above)
Comment (foolwc) [reply web/cypress/integration/service/create-service-with-chash-upstream.spec.js]: Thanks for your invaluable guidance. I copied `cy.wait` from another test file so I just removed it and the test case can  also work. Please help me review my code again. Thanks a lot.

**Comment by liuxiran** [comment]
Nice work @foolwc , let's wait for CI
Also cc @guoqqqi @iamayushdas to take a look. 

Thanks~

**Review by liuxiran — APPROVED** [review]

File: web/cypress/integration/route/create-route-with-chash-upstream.spec.js [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+    new_key: 'new_key',
+  };
+
+  beforeEach(() => {
+    cy.login();
+  });
+
+  it('should create route with custom chash key Upstream', function () {
+    cy.visit('/');
+    cy.get('[role=menu]')
```
Comment (guoqqqi) [inline web/cypress/integration/route/create-route-with-chash-upstream.spec.js:51]:
```suggestion
    cy.get('selector.XXX')
```
It is best to keep the context consistent when you use `selector.xxx`

File: web/cypress/integration/route/create-route-with-chash-upstream.spec.js [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+
+    cy.contains('Next').click().click();
+    cy.get(selector.name).type(data.routeName);
+    cy.contains('Next').click();
+
+    cy.get('[title="Round Robin"]').click();
+    cy.get(selector.upstreamType).within(() => {
+      cy.contains('CHash').click();
+    });
+    cy.get('[title="vars"]').click();
```
Comment (guoqqqi) [inline web/cypress/integration/route/create-route-with-chash-upstream.spec.js:66]: ditto

File: web/cypress/integration/route/create-route-with-chash-upstream.spec.js [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+    cy.get(selector.hashPosition).within(() => {
+      cy.contains('cookie').click();
+    });
+    cy.get('[value="remote_addr"]').click();
+    cy.get('[value="remote_addr"]').clear().type(data.custom_key);
```
Comment (guoqqqi) [inline web/cypress/integration/route/create-route-with-chash-upstream.spec.js:71]: ditto

File: web/cypress/integration/service/create-service-with-chash-upstream.spec.js [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+    cy.login();
+  });
+
+  it('should create a service with custom CHash key Upstream', function () {
+    cy.visit('/');
+    cy.contains('Service').click();
+    cy.contains('Create').click();
+    cy.get(selector.name).type(data.serviceName);
+    cy.get(selector.description).type(data.description);
+    cy.get('[title="Round Robin"]').click();
```
Comment (guoqqqi) [inline web/cypress/integration/service/create-service-with-chash-upstream.spec.js:59]: ditto

File: web/cypress/integration/service/create-service-with-chash-upstream.spec.js [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+    cy.get(selector.upstreamType).within(() => {
+      cy.contains('CHash').click();
+    });
+    cy.get('[title="vars"]').click();
+    cy.get(selector.hashPosition).within(() => {
+      cy.contains('cookie').click();
+    });
+    cy.get('[value="remote_addr"]').click();
+    cy.get('[value="remote_addr"]').clear().type('custom_key');
```
Comment (guoqqqi) [inline web/cypress/integration/service/create-service-with-chash-upstream.spec.js:68]: ditto

File: web/cypress/integration/upstream/create_and_edit_upstream_with_custom_chash_key.spec.js [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+
+  it('should create upstream with custom chash key', function () {
+    cy.visit('/');
+    cy.contains('Upstream').click();
+    cy.contains('Create').click();
+
+    cy.get(selector.name).type(data.upstreamName);
+    cy.get(selector.description).type(data.description);
+
+    cy.get('[title="Round Robin"]').click();
```
Comment (guoqqqi) [inline web/cypress/integration/upstream/create_and_edit_upstream_with_custom_chash_key.spec.js:58]: ditto

File: web/cypress/integration/route/create-route-with-chash-upstream.spec.js (hunk 3 above)
Comment (foolwc) [reply web/cypress/integration/route/create-route-with-chash-upstream.spec.js]: Thank you for the guidance of the code standards. Please help me review again. @guoqqqi

**Review by guoqqqi — APPROVED** [review]

File: web/cypress/integration/route/create-route-with-chash-upstream.spec.js [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+    cy.get(selector.hashPosition).within(() => {
+      cy.contains('cookie').click();
+    });
+    cy.get(selector.defaultCHashKey).click();
+    cy.get(selector.defaultCHashKey).clear().type(data.custom_key);
+    cy.get(selector.nodes_0_host).click();
+    cy.get(selector.nodes_0_host).type(data.ip);
+    cy.get(selector.nodes_0_port).clear().type(data.port);
+    cy.get(selector.nodes_0_weight).clear().type(data.weight);
+
```
Comment (LiteSun) [inline web/cypress/integration/route/create-route-with-chash-upstream.spec.js:80]:
```suggestion
```

**Review by LiteSun — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by liuxiran** [comment]
merged, thanks for your contribution @foolwc
