### PR TITLE
fix: mask sensitive fields

### LINKED ISSUE #3218: bug: Sensitive keys and tokens are visible in the APISIX Dashboard
### Current Behavior

While using the APISIX Dashboard, I noticed that sensitive fields such as admin keys and secret vault tokens are displayed in plain text. This poses a potential security risk, as anyone with access to the dashboard UI can easily see and copy these credentials.

### Expected Behavior

Sensitive fields (e.g., keys, tokens, secrets) should be masked or hidden by default, similar to how password fields are handled. Ideally, the dashboard should display these fields as password-type fields (•••••).

### Error Logs

_No response_

### Steps to Reproduce

1. Log in to the APISIX Dashboard.
2. Navigate to configuration sections where sensitive values are managed (e.g., admin key, secret vault tokens, or similar).
3. Observe that the values are shown in plain text without any masking

### Environment

- APISIX version (run `apisix version`): 3.13
- Operating system (run `uname -a`): Linux - Docker
- APISIX Dashboard version, if relevant: 3.13

### PR DESCRIPTION
**Pull request by ysinghc**
**Why submit this pull request?**

- [x] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

This PR enhances security by masking sensitive data fields in the APISIX Dashboard UI:

### Changes Made:

1. **New PasswordInput Component** (PasswordInput.tsx)
   - Created a reusable form component for sensitive data fields
   - Built on Mantine's PasswordInput with proper form validation integration
   - Supports reveal/hide toggle for user convenience while maintaining security

2. **Updated Secret Management Forms** (FormPartSecret.tsx)
   - Replaced TextInput with PasswordInput for sensitive fields:
     - **Vault secrets**: `token` field
     - **AWS secrets**: `access_key_id`, `secret_access_key`, `session_token` fields
     - **GCP secrets**: `private_key` field

3. **Updated Settings Modal** (SettingsModal.tsx)
   - Changed Admin Key input from TextInput to PasswordInput
   - Prevents accidental exposure of admin credentials

4. **Updated E2E Tests**
   - Modified test selectors in auth.spec.ts to work with PasswordInput component
   - Updated test.ts authentication helper to use proper selectors

5. **Code Consistency** (i18n.ts)
   - Reordered import statements alphabetically for better maintainability

### Security Benefits:
- Passwords, tokens, and keys are now masked by default
- Reduces risk of shoulder surfing and accidental exposure
- Maintains usability with toggle visibility option
- Consistent UX across all sensitive field inputs

**Related issues**

fixes #3218 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
  - **Problem**: Sensitive data (passwords, API keys, tokens) was displayed in plain text in form fields, creating a security risk
  - **Solution**: Implemented masked password inputs with toggle visibility for all sensitive fields
  
- [x] Have you added corresponding test cases?
  - Updated E2E tests in auth.spec.ts and test.ts to work with the new PasswordInput component
  
- [ ] Have you modified the corresponding document?
  - No documentation changes required as this is a UI improvement that doesn't change the API or user workflows
  
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first
  - **Yes, fully backward compatible**. This change only affects the UI rendering of form inputs. All data handling, API interactions, and existing configurations remain unchanged.

### CODE REVIEW

File: src/config/i18n.ts [hunk 1]
```diff
@@ -19,8 +19,8 @@ import { initReactI18next } from 'react-i18next';
 
 import de_common from '@/locales/de/common.json';
 import en_common from '@/locales/en/common.json';
-import zh_common from '@/locales/zh/common.json';
 import es_common from '@/locales/es/common.json'; 
+import zh_common from '@/locales/zh/common.json';
```
Comment (Baoyuantop) [inline src/config/i18n.ts]: Why is this change needed?

**Review by Baoyuantop — COMMENTED** [review]
Another test is needed to verify the password input field switching between showing and hiding.

File: src/config/i18n.ts (hunk 1 above)
Comment (ysinghc) [reply src/config/i18n.ts]: Its not a fix, just a nitpick, made it in the alphabetical order.
