### PR TITLE
fix: promethus incorrect value when update route

### LINKED ISSUE #627: Route update prompts: scheme validate failed: (root): Additional property enabled is not allowed
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

Bug with routing updates. When the prometheus plugin is enabled, update route request prompts: `scheme validate failed: (root): Additional property enabled is not allowed`

路由更新时的 bug，当 prometheus 插件开启的时候，更新路由时会提示：`scheme validate failed: (root): Additional property enabled is not allowed`

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bugfix
- Description
 Put incorrect Prometheus value when update route. 
 resolved #627 

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

File: frontend/src/pages/Route/transform.ts [hunk 1]
```diff
@@ -152,10 +152,6 @@ export const transformRouteData = (data: RouteModule.Body) => {
 
   const { plugins, script } = data;
 
-  if (plugins && plugins.prometheus) {
-    plugins.prometheus = { enabled: true };
```
Comment (juzhiyuan) [inline frontend/src/pages/Route/transform.ts:156]: If we remove this line, and just enabled this plugin, then how about this plugin's status when we use Edit mode? Is it still enabled?

Comment (LiteSun) [reply frontend/src/pages/Route/transform.ts:156]: > If we remove this line, and just enabled this plugin, then how about this plugin's status when we use Edit mode? Is it still enabled?

When we in Edit mode, API will return `plugins:{promethues:{}}`if we enabled it before and it works as expected.

image

**Review by juzhiyuan — APPROVED** [review]
