### PR TITLE
fix: cannot delete multiple plugins without page refreshing

### LINKED ISSUE #1316: GlobalPlugin List: cannot delete multiple plugins without page refreshing
# Bug report

## Describe the bug

GlobalPlugin List: cannot delete multiple plugins without page refreshing.

## How to Reproduce

1. Go to GlobalPlugin (Plugin);
2. Click on Delete, then that plugin is deleted;
3. Click on Delete on another Plugin, then the deleted plugin (step2) is shown.

## System information

- Version: master branch

## Additional context

This is because, it will put the previous plugin's data when deleting another plugin.

### PR DESCRIPTION
**Pull request by guoqqqi**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

resolve #1316 
Update the plugin data after deleting a plugin

### CODE REVIEW

File: web/src/pages/Plugin/List.tsx [hunk 1]
```diff
@@ -79,6 +79,7 @@ const Page: React.FC = () => {
                 const plugins = omit(initialData, [`${record.name}`]);
                 createOrUpdate({ plugins }).then(() => {
                   ref.current?.reload();
+                  setInitialData(plugins);
```
Comment (juzhiyuan) [inline web/src/pages/Plugin/List.tsx:82]: testcase, please.

Comment (juzhiyuan) [reply web/src/pages/Plugin/List.tsx:82]: The test case needs to make sure it could delete multiple plugins successfully.

File: web/cypress/fixtures/pluginList.json [hunk 2]
```diff
@@ -0,0 +1,41 @@
+{
```
Comment (juzhiyuan) [inline web/cypress/fixtures/pluginList.json:1]: The file name should be like `a-b-c.json`

Comment (juzhiyuan) [reply web/cypress/fixtures/pluginList.json:1]: and why not use data from another schema data file?

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+    empty: '.ant-empty-normal',
+  };
+
+  beforeEach(() => {
+    cy.login();
+
+    cy.fixture('pluginList.json').as('cases');
+  });
+
+  it('should create plugin', () => {
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:36]:
```suggestion
  it('should create plugins', () => {
```

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+    cy.visit('/');
+    cy.contains('Plugin').click();
+    cy.contains('Create').click();
+
+    cy.get(domSelectors.name).then(function (cards) {
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:41]: How about making this function global?

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+    cy.fixture('plugin-list.json').as('cases');
+  });
+
+  it('should create plugins', () => {
+    cy.visit('/');
+    cy.contains('Plugin').click();
+    cy.contains('Create').click();
+
+    // add test plugins
+    cy.addPlugins();
```
Comment (LiteSun) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:37]: what does `addPlugins`  mean?  Did you mean `testPlugins`?

Comment (juzhiyuan) [reply web/cypress/integration/plugin/create_and_delete_plugin.spec.js:37]: https://github.com/apache/apisix-dashboard/pull/1317/files#diff-5b8ddd39c2c1c0c56ef78ba6284324b57b0660d1d0eb5569cf59acf760fecd3bR38

File: web/cypress/support/commands.js [hunk 6]
```diff
@@ -34,3 +34,81 @@ Cypress.Commands.add('login', () => {
     localStorage.setItem('umi_locale', 'en-US');
   });
 });
+
+Cypress.Commands.add('addPlugins', () => {
```
Comment (juzhiyuan) [inline web/cypress/support/commands.js:38]: This function would better receive a parameter `cases`

File: web/cypress/support/commands.js [hunk 7]
```diff
@@ -35,7 +35,7 @@ Cypress.Commands.add('login', () => {
   });
 });
 
-Cypress.Commands.add('addPlugins', () => {
+Cypress.Commands.add('addPlugins', (cases) => {
```
Comment (juzhiyuan) [inline web/cypress/support/commands.js:38]: `cases` is an array (variable), and should replace `this.cases`.

Comment (juzhiyuan) [reply web/cypress/support/commands.js:38]: ping

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+    cy.fixture('plugin-list.json').as('cases');
+  });
+
+  it('should create plugins', function () {
+    cy.visit('/');
+    cy.contains('Plugin').click();
+    cy.contains('Create').click();
+
+    // add test plugins
+    cy.addPlugins(this.cases);
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:37]: not a good name, `configurePlugins`

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+context('Create and Delete Plugin List', () => {
+  const domSelectors = {
+    tableCell: '.ant-table-cell',
+    empty: '.ant-empty-normal',
+  };
+
+  beforeEach(() => {
+    cy.login();
+
+    cy.fixture('plugin-list.json').as('cases');
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:28]: why not use https://github.com/guoqqqi/apisix-dashboard/blob/fix-globalPlugin/web/cypress/fixtures/plugin-dataset.json and choose part of cases?

File: web/cypress/support/commands.js [hunk 10]
```diff
@@ -34,3 +34,81 @@ Cypress.Commands.add('login', () => {
...
+
+  cy.get(domSelectors.name).then(function (cards) {
+    [...cards].forEach((card) => {
+      const name = card.innerText;
+      const pluginCases = cases[name] || [];
+      // eslint-disable-next-line consistent-return
+      pluginCases.forEach(({ shouldValid, data, type = '' }) => {
+        /**
+         * NOTE: This test is mainly for GlobalPlugin, which is using non-consumer-type schema.
+         */
```
Comment (juzhiyuan) [inline web/cypress/support/commands.js:56]: No need those tips

Comment (juzhiyuan) [reply web/cypress/support/commands.js:56]: because this is a public function

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
@guoqqqi CI failed

File: web/cypress/integration/plugin/schema-smocktest.spec.js [hunk 11]
```diff
@@ -31,6 +31,7 @@ context('smoke test for plugin schema', () => {
     cy.contains('Plugin').click();
     cy.contains('Create').click();
 
+    // add test plugins
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/schema-smocktest.spec.js:34]: If your codes are clear, no need to add this tip.

File: web/cypress/integration/plugin/create_and_delete_plugin.spec.js [hunk 12]
```diff
@@ -40,15 +42,15 @@ context('Create and Delete Plugin List', () => {
   it('should delete plugin list', () => {
     cy.visit('/');
     cy.contains('Plugin').click();
-
-    cy.wait(500);
+
```
Comment (juzhiyuan) [inline web/cypress/integration/plugin/create_and_delete_plugin.spec.js:45]: extra spaces

File: web/cypress/support/commands.js [hunk 13]
```diff
@@ -65,6 +65,7 @@ Cypress.Commands.add('configurePlugins', (cases) => {
           });
 
         // NOTE: wait for the Drawer to appear on the DOM
+        cy.get({ timeout });
```
Comment (juzhiyuan) [inline web/cypress/support/commands.js:68]: get what?

**Review by juzhiyuan — CHANGES_REQUESTED** [review]
get what?

File: web/cypress/support/commands.js (hunk 13 above)
Comment (guoqqqi) [reply web/cypress/support/commands.js:68]: image
We can use timeout to replace those useless wait

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Comment by juzhiyuan** [comment]
@guoqqqi CI failed

**Comment by guoqqqi** [comment]
Hi，I will fix it at https://github.com/apache/apisix-dashboard/pull/1372
