### PR TITLE
fix:align dashboard menu options to the left

### LINKED ISSUE #1335: Align dashboard menu options to the left
# Bug report

## Describe the bug

I deployed the latest version of dashboard v2.3, and found that the `Server Info` in the left menu bar is not aligned, and the icons and text titles are displayed misaligned. And the content displayed in the `Server Info` is not very friendly. I hope that `last_report_time ` and `boot_time` do not use Unix Timestamp to display. In addition, the etcd version number obtained by `etcd_version` is not exactly the same as the actual version number used.

## System information

- OS: `CentOS Linux release 7.7.1908 (Core)`
- Browser: `Chrome/78.0.3904.108`
- Version: `apisix-dashboard-2.3`

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
fix #1335
___
### Bugfix
- Description
Align dashboard menu options to the left 

- How to fix?
I have added an infocircle icon at iconfont.js and updated helpers.tsx.

### CODE REVIEW

**Comment by KishaniKandasamy** [comment]
" Align dashboard menu options to the left"
Screenshot (34)

**Review by juzhiyuan — APPROVED** [review]

File: web/src/libs/iconfont.js [hunk 1]
```diff
@@ -30,7 +30,7 @@
...
...08-8.557887-2.334189-16.338113-5.446038-16.338114-13.226264v-49.790793c0-8.557887 7.002566-14.003925 15.560453-14.003924h1.556529c21.784151 0.77766 66.128906 4.668377 87.911849 4.668377 33.453887 0 50.56966-9.336755 61.461736-49.792l6.223698-23.339471h-11.669736c-22.561811 0-50.56966-5.446038-67.685434-64.573585l-101.916981-356.319397c-0.77766-2.334189-0.77766-3.889509-0.777661-5.446037 0-7.780226 4.668377-12.447396 14.782793-12.447397h78.576302c7.002566 0 13.226264 7.001358 14.781585 14.003925l78.577509 316.641811c3.111849 13.226264 6.223698 17.115774 10.892075 17.115774h7.001359l84.023547-334.536453c1.555321-7.001358 7.779019-13.225057 15.559245-13.225057h79.35517c7.780226 0 14.003925 6.223698 14.003925 13.225057z" fill="#1890FF" ></path><path d="M3643.813434 155.203623c21.086189-4.692528 42.908981-7.631698 64.788528-8.777661 219.435472-11.499472 406.839547 158.192302 418.404227 378.855849 3.95834 75.522415-14.055849 150.439849-50.383698 215.553208 154.855849-55.217509 259.634717-206.250264 250.596226-378.724227-11.004377-209.968302-189.681509-371.759094-398.479698-360.815094-114.165132 5.982189-218.470642 63.932377-284.925585 153.907925z" fill="#D8D8D8" ></path></symbol></svg>',
```
Comment (liuxiran) [inline web/src/libs/iconfont.js:33]: it seems that `icondashboard` is used for `metrics` menu item, so you would better add new `svg` for `server_info` instead of cover the `icondashboard`

Comment (liuxiran) [inline web/src/libs/iconfont.js:33]: maybe we need to find a better way to store a self defined icon, it is a little hard to maintenance IMHO.

cc @juzhiyuan @LiteSun @guoqqqi

**Review by liuxiran — APPROVED** [review]
