### PR TITLE
fix: drawer components delete plugin not working

### LINKED ISSUE #2572: The drawer component cannot delete plugins
### Issue description

The plugin drawer component could not remove the enable plugin.

### Expected behavior

When the user clicks the delete button in the drawer component, the plugin should be deleted correctly

### How to Reproduce

pass

### Screenshots

22f485cdc906a25f9b0168c334e2775

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Morakes**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #2572 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: web/src/components/Plugin/PluginPage.tsx [hunk 1]
```diff
@@ -277,12 +277,12 @@ const PluginPage: React.FC<Props> = ({
...
       }}
       onChange={({ monacoData, formData, shouldDelete }) => {
-        let newPlugins = {
+        const newPlugins = {
           ...initialData,
           [name]: { ...monacoData, disable: !formData.disable },
         };
         if (shouldDelete === true) {
-          newPlugins = omit(newPlugins, name);
+          newPlugins[name] = null;
```
Comment (guoqqqi) [inline web/src/components/Plugin/PluginPage.tsx:285]: This method is not very good, we do not usually modify the value of an object's properties directly.
An extended question, we should normally have an indication of successful deletion when we delete data.

Comment (Morakes) [reply web/src/components/Plugin/PluginPage.tsx:285]: OK ,I will modify it again.

File: web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js [hunk 2]
```diff
@@ -109,4 +109,42 @@ context('Delete Plugin List with the Drawer', () => {
...
+        cy.get(selector.disabledSwitcher).click();
+        cy.get(selector.checkedSwitcher).should('exist');
+      });
+    cy.contains('button', 'Submit').click();
+
+    cy.contains(data.basicAuthPlugin)
+      .parents(selector.pluginCardBordered)
+      .within(() => {
+        cy.get('button').click({
+          force: true,
```
[the remark this answers is not in the document]
Comment (Morakes) [reply web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js:141]: If you don't use force it will make the test unstable.

File: web/src/pages/Plugin/PluginMarket.tsx [hunk 3]
```diff
@@ -48,14 +48,21 @@ const PluginMarket: React.FC = () => {
...
                 ...pluginsData,
               },
             }).then(() => {
               initPageData();
+              notification.success({
+                message: `${formatMessage({
+                  id: `component.global.${handleType}`,
+                })} ${formatMessage({
+                  id: 'menu.plugin',
+                })} ${formatMessage({ id: 'component.status.success' })}`,
```
Comment (guoqqqi) [inline web/src/pages/Plugin/PluginMarket.tsx:64]: ditto

File: web/src/pages/Plugin/List.tsx [hunk 4]
```diff
@@ -131,6 +131,13 @@ const Page: React.FC = () => {
           setVisible(false);
           setName('');
           ref.current?.reload();
+          notification.success({
+            message: `${formatMessage({
+              id: `component.global.${shouldDelete ? 'delete' : 'edit'}`,
+            })} ${formatMessage({
+              id: 'menu.plugin',
+            })} ${formatMessage({ id: 'component.status.success' })}`,
```
Comment (guoqqqi) [inline web/src/pages/Plugin/List.tsx:139]: This writing style will result in a Chinese state with extra spaces

File: web/src/components/Plugin/PluginPage.tsx [hunk 5]
```diff
@@ -280,11 +284,10 @@ const PluginPage: React.FC<Props> = ({
...
           ...initialData,
           [name]: { ...monacoData, disable: !formData.disable },
+          ...(shouldDelete ? { [name]: null } : {}),
         };
-        if (shouldDelete === true) {
-          newPlugins[name] = null;
-        }
-        onChange(newPlugins, form.getFieldValue('plugin_config_id'));
+        const handleType = shouldDelete ? 'delete' : 'edit';
+        onChange(newPlugins, handleType, form.getFieldValue('plugin_config_id'));
```
Comment (guoqqqi) [inline web/src/components/Plugin/PluginPage.tsx:290]: Please check the code here, I think it is the data there that is having an effect, we may not need to pass the `initialData` data. The onChange logic here I don't think should be changed, but the source of the problem should be looked at.
https://github.com/apache/apisix-dashboard/blob/master/web/src/pages/Plugin/PluginMarket.tsx#L54

File: web/src/components/Plugin/PluginPage.tsx [hunk 6]
```diff
@@ -280,11 +284,10 @@ const PluginPage: React.FC<Props> = ({
         const newPlugins = {
           ...initialData,
           [name]: { ...monacoData, disable: !formData.disable },
+          ...(shouldDelete ? { [name]: null } : {}),
```
Comment (guoqqqi) [inline web/src/components/Plugin/PluginPage.tsx:287]: As this component is used in a number of places, we need to be extra careful in modifying this part of the code

**Comment by guoqqqi** [comment]
also cc @SkyeYoung @Baoyuantop PTAL

File: web/src/components/Plugin/PluginPage.tsx (hunk 5 above)
Comment (Morakes) [reply web/src/components/Plugin/PluginPage.tsx:290]: Well, based on your hints, I think I've found the root cause，thank you.

**Comment by guoqqqi** [comment]
also cc @SkyeYoung PTAL

File: web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (LiteSun) [reply web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js:141]: Perhaps it would be better to use a more precise selector?

**Review by SkyeYoung — APPROVED** [review]

File: web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js [hunk 7]
```diff
@@ -107,6 +109,48 @@ context('Delete Plugin List with the Drawer', () => {
...
+      });
+
+    cy.contains('button', 'Delete').click({
+      force: true,
+    });
+    cy.contains('button', 'Confirm').click({
+      force: true,
+    });
+    cy.get(selector.notification).should('contain', 'Delete Plugin Successfully');
+    cy.get(selector.notificationCloseIcon).click({ multiple: true });
```
Comment (Baoyuantop) [inline web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js:152]: After that, we would better check that the plugin button is turned to `Enable` instead of `Edit`

File: web/src/pages/Plugin/PluginMarket.tsx [hunk 8]
```diff
@@ -48,14 +48,18 @@ const PluginMarket: React.FC = () => {
           initialData={initialData}
           type="global"
           schemaType="route"
-          onChange={(pluginsData) => {
+          onChange={(pluginsData, pluginId, handleType) => {
             createOrUpdate({
               plugins: {
-                ...initialData,
                 ...pluginsData,
               },
```
Comment (Baoyuantop) [inline web/src/pages/Plugin/PluginMarket.tsx:55]: If there is only one left, there is no need to expand the operation.

File: web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js (hunk 7 above)
Comment (Morakes) [reply web/cypress/integration/plugin/create-delete-in-drawer-plugin.spec.js:152]: OK, I'll improve it.

**Review by oil-oil — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]
