### PR TITLE
fix: only auth type plugin need to configure

### LINKED ISSUE #1975: bug: error using the openid-connect plugin
## Issue description

The data editor suggests that no configuration is required, but after submission it shows that the clinet_id property must be configured, which is contradictory.

take a look at Screenshots
## Screenshots

image

## Environment

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.7
* Browser version, if have:

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
only auth type plugin need to configure

**Related issues**

resolve #1975 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by iamayushdas — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by iamayushdas — APPROVED** [review]

File: web/src/components/Plugin/service.ts [hunk 1]
```diff
@@ -34,6 +34,7 @@ export const fetchList = () => {
     const typedData = data.data.map(item => ({
       ...item,
       type: PLUGIN_LIST[item.name]?.type || "other",
```
Comment (liuxiran) [inline web/src/components/Plugin/service.ts:36]: Does `type` props still be used?

**Review by liuxiran — APPROVED** [review]

File: web/src/components/Plugin/service.ts (hunk 1 above)
Comment (juzhiyuan) [reply web/src/components/Plugin/service.ts:36]: need @LiteSun to have a search

Comment (LiteSun) [reply web/src/components/Plugin/service.ts:36]: > Does type props still be used? If not we can delete it ^^

Type props still are used.

**Review by bzp2010 — APPROVED** [review]
