### PR TITLE
fix: add defer recover for go routines to prevent abnormal crash

### LINKED ISSUE #838: Bug: Add defer recover for all go routines to prevent abnormal crash of manager-api
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
2.0

- What happened?
Manager-api may crash without any logs.
In gin, we use `filter.RecoverHandler()` to prevent crash. 
But we can not control the exceptions in other go-routines.
Need to add `defer recover()` for all go routines to prevent abnormal crash of manager-api .

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
close #838
___
### Bugfix
- Description

Manager API may crash without any logs.
In gin, we use filter.RecoverHandler() to prevent crash.
But we can not control the exceptions in other go-routines.

- How to fix?

 add defer recover() for go routines to prevent abnormal crash

### CODE REVIEW

File: api/internal/utils/runtime/runtime.go [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+func HandlePanic(additionalHandlers ...func(interface{})) {
+	if err := recover(); err != nil {
+		for _, fn := range PanicHandlers {
+			fn(err)
+		}
+		for _, fn := range additionalHandlers {
+			fn(err)
+		}
+		if ActuallyPanic {
```
Comment (starsz) [inline api/internal/utils/runtime/runtime.go:40]: ActuallyPanic is true? So what's the meaning of HandlePanic?
Just for log the stack?

**Review by starsz — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]
