### PR TITLE
fix: efficient error handling in manager-api including graceful shutdown, self contained methods.

### LINKED ISSUE #1684: program panic when failed to initialize etcd store is unreasonable
## Issue description

Say my etcd cluster contains some corrupted data, which causes the manager api launching failed, the manager-api just crashes and the output is not so friendly.

## Expected behavior

Output some messages to hint at this failure and exit.

## Screenshots

image

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.5.0-alpha0
* apisix-dashboard version, if have: 2.5
* Browser version, if have:

### PR DESCRIPTION
**Pull request by bisakhmondal**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
#### 4. Removing unnecessary proliferation of golang `panic`s. Why not use the user friendly interface already provided by cobra. To be honest, output of `panic` looks scary 😂

5. Closing of all opened resource has been put into deferred execution. So incase any panic occurs during runtime, the respective closers of the resource gets executed safely. Till now, for panics, the main goroutine was getting closed ungracefully.

6. Detailed error description if etcd contains corrupted data and exit with nonzero error code.
image

**Related issues**
reopening #1705 
closes #1684 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by bisakhmondal** [comment]
@nic-chen still same issue. any idea why? this time I pull the master, created a new branch and handpicked the new lines (as the number of lines were less) of commit instead of cherry-picking to avoid this CI invocation, but still the same problem

**Comment by juzhiyuan** [comment]
Hi, I just sent an email to GitHub Support, to ask for their help about this case.

**Comment by bisakhmondal** [comment]
Nice🔥

**Comment by nic-chen** [comment]
I can't think of why. This should be the same as other new PRs, but other PRs have no such problem. Just wait for the reply from GitHub Support..

**Comment by bisakhmondal** [comment]
Hii, any update :)

**Comment by nic-chen** [comment]
hi @bisakhmondal  please sync code from branch master

**Comment by bisakhmondal** [comment]
Thanks!! Done.

**Comment by bisakhmondal** [comment]
Ou Nice!! It seems no stalling CI from node build. Thank you both :)

File: api/cmd/managerapi.go [hunk 1]
```diff
@@ -65,6 +66,14 @@ func printVersion() {
 
 // NewManagerAPICommand creates the manager-api command.
 func NewManagerAPICommand() *cobra.Command {
+	cobra.OnInitialize(func() {
+		var err error
+		service, err = createService()
```
Comment (tokers) [inline api/cmd/managerapi.go:71]: Use short variables creation.

Comment (bisakhmondal) [reply api/cmd/managerapi.go:71]: Hi @tokers, I'm afraid that's not possible here due to variable shadowing.

`service` is a global variable and assignment through go's short assignment operator (`:=`) will create a brand new `service` var in this scope without referencing the global one.

I looked into the docs and also cross-checked [ref](https://golang.org/ref/spec#Declarations_and_scope)
>An identifier declared in a block may be redeclared in an inner block. While the identifier of the inner declaration is in scope, it denotes the entity declared by the inner declaration.

Anyway, Thank you. Got the scope to re-read the docs :)

Comment (bisakhmondal) [reply api/cmd/managerapi.go:71]: Wait, what!! that's not from this PR 🤔

**Comment by bisakhmondal** [comment]
Any idea why the upstream test suite is breaking🤔, the PR doesn't touch anything on that segment and moreover, it's HTTP 400!!

All starts with `test upstream delete [It] create upstream without plugin ` i.e failing to process upstream request and rest (other tests) is dominos effect.

But it's working fine locally
Screenshot from 2021-05-04 20-09-42

**Review by tokers — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Hi @bisakhmondal, it seems that there have some errors in Backend CI.

**Comment by bisakhmondal** [comment]
> Hi @bisakhmondal, there have some errors in Backend CI.

Yeshh!! Sad moments🥺
Looking into it :)

File: api/internal/utils/pid.go [hunk 2]
```diff
@@ -26,6 +26,9 @@ import (
 
 // WritePID write pid to the given file path.
 func WritePID(filepath string) error {
+	if _, err := os.Stat(filepath); err == nil {
+		return fmt.Errorf("instance of Manager API already running: a pid file exists in %s", filepath)
```
Comment (starsz) [inline api/internal/utils/pid.go:30]: Does this mean the manager can't start successfully if there exists a PID file?

Comment (tokers) [reply api/internal/utils/pid.go:30]: We may add an option to start forcely.

Comment (bisakhmondal) [reply api/internal/utils/pid.go:30]: Hii guys, as we are now supporting manager-api as an os service, the PID file should not be overwritten unknowingly, because then `./manager-api stop` won't work. we have to take help from the os service manager explicitly.

> We may add an option to start forcely.
Yes, we can do that.

**Review by nic-chen — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Comment by juzhiyuan** [comment]
@bisakhmondal Hi, if it's ok, could you please send a new PR to fix that failure?

**Comment by bisakhmondal** [comment]
> @bisakhmondal Hi, if it's ok, could you please send a new PR to fix that failure?

Ya, that sounds awesome.

but yet, I can't reproduce the failure(totally irrelevant to this PR) locally even with the same environment like CI inside a docker container,
image

**Comment by bisakhmondal** [comment]
> @bisakhmondal Hi, if it's ok, could you please send a new PR to fix that failure?

@juzhiyuan It seems to be a CI glitch, now the master is fine after a recent commit.
image


Even the last commit has passed all CI. What do you think, can we ignore?

**Comment by juzhiyuan** [comment]
I have to say it's unstable, please create an issue to track this :)
