### PR TITLE
fix: used dashboard add consumer of jwt, would have an error when get the jwt token 

### LINKED ISSUE #759: bug: used dashboard add consumer of jwt, would have an error when get the jwt token
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

used dashboard add consumer of jwt, would have an error when get the jwt token
```
2020/11/10 10:51:19 [error] 25300#2021499: *20001 lua entry thread aborted: runtime error: /Users/idbeta/1106/apisix/apisix/plugins/jwt-auth.lua:177: attempt to perform arithmetic on field 'exp' (a nil value)
stack traceback:
coroutine 0:
	/Users/idbeta/1106/apisix/apisix/plugins/jwt-auth.lua: in function 'sign_handler'
	/Users/idbeta/1106/apisix/apisix/plugins/jwt-auth.lua:299: in function 'handler'
	/Users/idbeta/1106/apisix/apisix/api_router.lua:108: in function 'handler'
	...beta/1106/apisix//deps/share/lua/5.1/resty/radixtree.lua:775: in function 'dispatch'
	/Users/idbeta/1106/apisix/apisix/api_router.lua:134: in function 'match'
	/Users/idbeta/1106/apisix/apisix/init.lua:379: in function 'http_access_phase'
	access_by_lua(nginx.conf:177):2: in main chunk, client: 127.0.0.1, server: , request: "GET /apisix/plugin/jwt/sign?key=dd HTTP/1.1", host: "127.0.0.1:9080"
``` 
the etcd data
```
{"id":"test_jwt","create_time":1604976497,"update_time":1604976497,"username":"test_jwt","plugins":{"jwt-auth":{"algorithm":"HS256","base64_secret":false,"key":"dd","secret":"my-secret-key"}}}
```
relate https://github.com/apache/apisix/issues/2649

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

fix #759

### CODE REVIEW

File: api/internal/handler/consumer/consumer.go [hunk 1]
```diff
@@ -105,6 +105,13 @@ func (h *Handler) Create(c droplet.Context) (interface{}, error) {
 	}
 	input.ID = input.Username
 
+	if _, ok := input.Plugins["jwt-auth"]; ok {
+		jwt := input.Plugins["jwt-auth"].(map[string]interface{})
+		jwt["exp"] = 86400
```
Comment (gxthrj) [inline api/internal/handler/consumer/consumer.go:110]: why add exp = 86400？

Comment (nic-chen) [reply api/internal/handler/consumer/consumer.go:110]: Because there is a problem with the default value setting of the current jsonschema, a temporary solution

**Review by gxthrj — APPROVED** [review]

File: api/internal/handler/consumer/consumer.go (hunk 1 above)
Comment (moonming) [reply api/internal/handler/consumer/consumer.go:110]: Please add issue for it
