### PR TITLE
fix: remove ssl check in redirect https

### LINKED ISSUE #2445: A question about redirect to https with  'lb + apisix'
### Discussed in https://github.com/apache/apisix/discussions/6928

<div type='discussions-op-text'>

<sup>Originally posted by **Lewisyixin** April 25, 2022</sup>
Is there any way to redirect from http  to https on apisix which behind a lb  meanwhile use http to proxy between lb and apisix?
We want to use apisix to replace nginx. Our nginx conf is about below..
Our ssl certs are on lb.  lb's 80 port proxy to nginx 80  port and 443 port proxy to nginx 443 port.
We just want to achieve the following conditions:

1. ssl cert just on lb and nginx 443 port is just a http port
2. redirection of https  is completed by nginx(because some domain don't want auto redirection)

`server{
        listen 80;
        server_name www.test.com;
        rewrite ^(.*)$ https://$host$1 permanent;
}

server {
        listen 443 ;
        server_name www.test.com;
}
`

I tried to complete this on apisix but I found that  a different  of apisix is that  mutiple http port can't handle different configs  like behand. So is there any to accomplish the goal？

</div>

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #2445 

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: web/src/pages/Route/Create.tsx [hunk 1]
```diff
@@ -260,17 +260,10 @@ const Page: React.FC<Props> = (props) => {
...
-              ? checkHostWithSSL(hosts)
-              : Promise.resolve(),
-            checkUniqueName(
-              value.name,
-              props.route.path.indexOf('edit') > 0 ? (props as any).match.params.rid : '',
-            ),
-          ]).then(() => {
+          checkUniqueName(
+            value.name,
+            props.route.path.indexOf('edit') > 0 ? (props as any).match.params.rid : '',
```
Comment (SkyeYoung) [inline web/src/pages/Route/Create.tsx:265]: type?

**Review by LiteSun — APPROVED** [review]

File: web/src/pages/Route/Create.tsx (hunk 1 above)
Comment (Baoyuantop) [reply web/src/pages/Route/Create.tsx:265]: This PR only deletes one function, and the rest of it is not expected to be changed.

**Review by SkyeYoung — APPROVED** [review]
