### PR TITLE
fix(route): add operators

### LINKED ISSUE #2014: support all operators in vars field
When creating a Route, we could use the `vars` field to allow more advanced match rules. 

image

There have 2 things we could improve:

- [ ] For each operator, we could support different actions on the `value` field. e.g when using the `IN` operator, we could use an Ant Design component that allows input values by clicking the Enter key.
- [ ] Check if we are missing some operators from https://github.com/api7/lua-resty-expr

Documentation: https://apisix.apache.org/docs/apisix/2.7/admin-api/#request-body-parameters

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

support all operators in route vars field .

**Related issues**

fix #2014 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — COMMENTED** [review]
Please don't modify unchanged codes.

File: web/src/pages/Route/components/Step1/MatchingRulesView.tsx [hunk 1]
```diff
@@ -245,30 +258,48 @@ const MatchingRulesView: React.FC<RouteModule.Step1PassProps> = ({
...
+                    break;
+                  case '~~':
+                    setOperatorValueSample(
+                      formatMessage({ id: 'page.route.advanced-match.operator.sample.~~' }),
+                    );
+                    break;
+                  case '~*':
+                    setOperatorValueSample(
+                      formatMessage({ id: 'page.route.advanced-match.operator.sample.~~' }),
+                    );
```
Comment (liuxiran) [inline web/src/pages/Route/components/Step1/MatchingRulesView.tsx:285]:
```suggestion
                  case '~~':
                  case '~*':
                    setOperatorValueSample(
                      formatMessage({ id: 'page.route.advanced-match.operator.sample.~~' }),
                    );
```

File: web/src/pages/Route/components/Step1/MatchingRulesView.tsx [hunk 2]
```diff
@@ -136,9 +136,18 @@ const MatchingRulesView: React.FC<RouteModule.Step1PassProps> = ({
           case '~~':
             renderText = formatMessage({ id: 'page.route.regexMatch' });
             break;
+          case '~*':
+            renderText = formatMessage({ id: 'page.royte.caseInsensitiveRegexMatch' });
+            break;
           case 'IN':
             renderText = formatMessage({ id: 'page.route.in' });
             break;
+          case 'HAS':
```
Comment (liuxiran) [inline web/src/pages/Route/components/Step1/MatchingRulesView.tsx:145]: How about try to use a cont object or enum to define the the relationship between the operator and its show name? this can also be reused in https://github.com/apache/apisix-dashboard/pull/2022/files#diff-a55e5a5bd491758bf28203f2e3eb5ada3d01944348e00c2cafb6671e79621bc3R288-R298

**Comment by liuxiran** [comment]
It would be better to add a test case to verify whether we have covered add the operators

File: web/src/pages/Route/components/Step1/MatchingRulesView.tsx (hunk 2 above)
Comment (Baoyuantop) [reply web/src/pages/Route/components/Step1/MatchingRulesView.tsx:145]: Think it's good, let me try

**Comment by Baoyuantop** [comment]
> It would be better to add a test case to verify whether we have covered add the operators

I am supplementing the test part

File: web/src/pages/Route/components/Step1/MatchingRulesView.tsx [hunk 3]
```diff
@@ -88,6 +88,18 @@ const MatchingRulesView: React.FC<RouteModule.Step1PassProps> = ({
     });
   };
 
+  const OperatorRenderText = {
+    '==': 'page.route.equal',
```
Comment (juzhiyuan) [inline web/src/pages/Route/components/Step1/MatchingRulesView.tsx:92]: Not a good idea to use `key` here directly, I would prefer keeping the `formatMessage(xxx)` here

Comment (Baoyuantop) [reply web/src/pages/Route/components/Step1/MatchingRulesView.tsx:92]: like `'==': formatMessage({ id: page.route.equal })` ?

Comment (juzhiyuan) [reply web/src/pages/Route/components/Step1/MatchingRulesView.tsx:92]: yes

**Review by guoqqqi — APPROVED** [review]

**Comment by guoqqqi** [comment]
LGTM! cc @liuxiran @iamayushdas please have a look

**Review by iamayushdas — APPROVED** [review]

File: web/src/pages/Route/locales/zh-CN.ts [hunk 4]
```diff
@@ -26,7 +26,10 @@ export default {
   'page.route.greaterThan': '大于（>）',
   'page.route.lessThan': '小于（<）',
   'page.route.regexMatch': '正则匹配（～～）',
+  'page.route.caseInsensitiveRegexMatch': '不区分大小写的正则匹配(~*)',
```
Comment (juzhiyuan) [inline web/src/pages/Route/locales/zh-CN.ts:29]:
```suggestion
  'page.route.caseInsensitiveRegexMatch': '不区分大小写的正则匹配（~*）',
```

**Review by juzhiyuan — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]
