### PR TITLE
fix: change regex template to optional in proxy write

### LINKED ISSUE #2381: proxy-rewrite.regex_uri need empty value to replaced
### Issue description

at dashboard when proxy-rewrite.regex-uri can't replace empty value;but use apisix api support empty value.
image

### Expected behavior

support empty value to replaced

### How to Reproduce

use dashboard plugin-rewrite plugin

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`): 2.12.1& dashboard lasted
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #2381 

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: web/src/pages/Route/components/Step1/ProxyRewrite.tsx [hunk 1]
```diff
@@ -100,14 +100,6 @@ const ProxyRewrite: React.FC<RouteModule.Step1PassProps> = ({ form, disabled })
                         label={formatMessage({ id: 'page.route.form.itemLabel.template' })}
                         name={field.name}
                         key={field.name}
-                        rules={[
```
Comment (guoqqqi) [inline web/src/pages/Route/components/Step1/ProxyRewrite.tsx:103]: Just to confirm, this change doesn't require a change to the API interface?

Comment (Baoyuantop) [reply web/src/pages/Route/components/Step1/ProxyRewrite.tsx:103]: Not required.

**Review by LiteSun — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]
