### PR TITLE
fix: hash_on field and limitation

### LINKED ISSUE #2012: check hash_on field and limitation
Visiting the Upstream creation or configuration page, you can see that the `Hash On` selector contains 5 options: vars, header, cookie, consumer, and vars_combination.

image

According to the documentation, when a different value is selected for this parameter, the other parameters will be linked, and it is necessary to check if the behavior is accurate.

image

Documentation: https://apisix.apache.org/docs/apisix/2.7/admin-api/#request-body-parameters-3

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

In the Upstream creation or configuration page, when Hash on selected `consumer`, the `Key` field is not required.

**Related issues**

fix #2012 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: web/src/components/Upstream/components/Type.tsx [hunk 1]
```diff
@@ -14,28 +14,34 @@
...
-import { AutoComplete, Form, Select } from 'antd'
-import { useIntl } from 'umi'
-import type { FormInstance } from 'antd/es/form'
+import React, { useState } from 'react';
+import { AutoComplete, Form, Select } from 'antd';
+import { useIntl } from 'umi';
+import type { FormInstance } from 'antd/es/form';
 
-import { HashOnEnum, CommonHashKeyEnum, AlgorithmEnum } from '../constant'
+import { HashOnEnum, CommonHashKeyEnum, AlgorithmEnum } from '../constant';
```
Comment (juzhiyuan) [inline web/src/components/Upstream/components/Type.tsx:22]: I would suggest linting all files in one PR, then submit your changes for this plugin.

Comment (Baoyuantop) [reply web/src/components/Upstream/components/Type.tsx:22]: I will try

Comment (Baoyuantop) [reply web/src/components/Upstream/components/Type.tsx:22]: #2035  @juzhiyuan

File: web/src/components/Upstream/components/Type.tsx [hunk 2]
```diff
@@ -52,7 +52,7 @@ const CHash: React.FC<Pick<Props, 'readonly'>> = ({ readonly }) => {
       </Form.Item>
       <Form.Item
         name="key"
-        rules={[{ required: true }]}
+        rules={[{ required: form.getFieldValue('hash_on') !== 'consumer' }]}
         label={formatMessage({ id: 'component.upstream.fields.key' })}
```
Comment (liuxiran) [inline web/src/components/Upstream/components/Type.tsx:56]: it would be better to add `disabled` attr to `key` field when user selected consumer, or hide this field is also a good choice

for when hash_on selected consumer, key will auto match current request's consumer automatically  no matter what user entered

**Review by liuxiran — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]
