### PR TITLE
fix: create upstream error when pass host is node and nodes without port

### LINKED ISSUE #2409: upstream config, cann't select Host header for option 'Keep the same Host from client request'
### Issue description

Config a upstream 
Upstream type : node
Hostname : somehost.com
when submit form, apisix dashboard backend will return 500.

```shell
binary-apisix-dashboard-1  | err； interface conversion: interface {} is map[string]interface {}, not []*entity.Node
binary-apisix-dashboard-1  | [Recovery] 2022/04/02 - 08:54:13 panic recovered:
binary-apisix-dashboard-1  | 
binary-apisix-dashboard-1  | interface conversion: interface {} is map[string]interface {}, not []*entity.Node
binary-apisix-dashboard-1  | /usr/local/go/src/runtime/iface.go:261 (0x40a5d4)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/core/store/validate.go:169 (0xbe328d)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/core/store/validate.go:226 (0xbe34b2)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/core/store/validate.go:253 (0xbe3609)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/core/store/store.go:249 (0xbdfa4a)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/core/store/store.go:315 (0xbe0204)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/handler/upstream/upstream.go:202 (0xc93b61)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware.go:18 (0x84ffab)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/base.go:16 (0xbedef4)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/traffic_log.go:73 (0xbedef5)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/base.go:16 (0xbebf8d)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/http_input.go:77 (0xbebf8e)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/base.go:16 (0xbed962)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/http_resp_reshap.go:19 (0xbed956)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/base.go:16 (0xbeec4e)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/handler/handler.go:81 (0xbeec42)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/base.go:16 (0xbebb61)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/middleware/http_injector.go:28 (0xbebb62)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet@v0.2.6-0.20210127040147-53817015cd1b/pipe.go:84 (0x8502a1)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/shiningrush/droplet/wrapper/gin@v0.2.1/gin.go:41 (0xbefd7e)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe923d)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/authentication.go:81 (0xbe8eaa)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe96ca)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/recover.go:53 (0xbe96b4)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbea510)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/schema.go:240 (0xbea3ea)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe670d)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/logging.go:35 (0xbe66f4)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe63f5)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/ip_filter.go:107 (0xbe6346)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe9c76)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/request_id.go:41 (0xbe9c5a)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xbe95f8)
binary-apisix-dashboard-1  | /usr/local/apisix-dashboard/api/internal/filter/cors.go:31 (0xbe95e4)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xc9602c)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-contrib/gzip@v0.0.3/handler.go:60 (0xc96002)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x9c7f04)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9c7b39)
binary-apisix-dashboard-1  | /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9c7673)
binary-apisix-dashboard-1  | /usr/local/go/src/net/http/server.go:2879 (0x6fe77a)
binary-apisix-dashboard-1  | /usr/local/go/src/net/http/server.go:1930 (0x6f9e27)
binary-apisix-dashboard-1  | /usr/local/go/src/runtime/asm_amd64.s:1581 (0x464ae0)
```

### Expected behavior

can be normal configed.

### How to Reproduce

 Config a upstream 
```
Upstream type : node
Hostname : somehost.com
```
when submit form, apisix backend will return 500.

### Screenshots

a6d

### Environment

- apisix version 2.12.1-centos, running in docker-compose from offical image
- OS (cmd: `uname -a`):  running in docker-compose from offical image
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  running in docker-compose from offical image
- etcd version, if have (cmd: run `etcd --version`): 3.4.18 (binary deylop)
- apisix-dashboard version, if have: 2.11.0, running in docker-compose from offical image
- Browser version, if have: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36

### Additional context

docker-compose does nothing, only mount some files to container

_No response_

### PR DESCRIPTION
**Pull request by jwrookie**
Signed-off-by: Wei Jiang <machowei01@gmail.com>

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
Create upstream should succeed when **pass_host** is `node` and **nodes** without `port`

**Related issues**

fix/resolve #2409

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by membphis** [comment]
typo in your title

image

File: api/internal/core/entity/format.go [hunk 1]
```diff
@@ -17,17 +17,23 @@
...
-	if err != nil {
-		log.Errorf("split host port fail: %s", err)
-		return nil, err
+	hp := strings.Split(key, ":")
+	host := hp[0]
+	//  according to APISIX upstream nodes policy, port is optional
+	port := "0"
+
+	if len(hp) > 2 {
+		return nil, errors.New("address typo error")
```
Comment (starsz) [inline api/internal/core/entity/format.go:34]:
```suggestion
		return nil, errors.New("invalid upstream node")
```

File: api/test/e2enew/upstream/upstream_test.go [hunk 2]
```diff
@@ -88,6 +88,24 @@ var _ = ginkgo.Describe("Upstream", func() {
...
+		gomega.Expect(err).To(gomega.BeNil())
+		base.RunTestCase(base.HttpTestCase{
+			Object:       base.ManagerApiExpect(),
+			Method:       http.MethodPut,
+			Path:         "/apisix/admin/upstreams/3",
+			Body:         string(_createUpstreamBody),
+			Headers:      map[string]string{"Authorization": base.GetToken()},
+			ExpectStatus: http.StatusOK,
+		})
+	})
```
[the remark this answers is not in the document]
Comment (nic-chen) [reply api/test/e2enew/upstream/upstream_test.go:108]: need a test case for DP

[the remark this answers is not in the document]
Comment (jwrookie) [reply api/test/e2enew/upstream/upstream_test.go:147]: Good idea. it is done now

**Review by starsz — APPROVED** [review]

**Review by nic-chen — COMMENTED** [review]
test failed @jwrookie

**Comment by jwrookie** [comment]
> test failed @jwrookie

Start the depend error, pls rerun it thanks

image

File: api/test/e2enew/upstream/upstream_test.go [hunk 3]
```diff
@@ -88,6 +88,63 @@ var _ = ginkgo.Describe("Upstream", func() {
 			ExpectStatus: http.StatusOK,
 		})
 	})
+	ginkgo.It("create upstream3 success when pass host is 'node' and nodes without port", func() {
+		ginkgo.By("create upstream3", func() {
+			createUpstreamBody := make(map[string]interface{})
+			createUpstreamBody["name"] = "upstream3"
+			createUpstreamBody["nodes"] = map[string]float64{base.UpstreamIp: 100}
```
Comment (nic-chen) [inline api/test/e2enew/upstream/upstream_test.go:95]: node for the test case still has port?

Comment (jwrookie) [reply api/test/e2enew/upstream/upstream_test.go:95]: Value(100) is weight, not port

Comment (nic-chen) [reply api/test/e2enew/upstream/upstream_test.go:95]: OK

**Review by nic-chen — APPROVED** [review]

**Comment by jwrookie** [comment]
@bzp2010  have a check, thanks!

File: api/internal/core/entity/format.go [hunk 4]
```diff
@@ -17,17 +17,23 @@
...
 
 func mapKV2Node(key string, val float64) (*Node, error) {
-	host, port, err := net.SplitHostPort(key)
-	if err != nil {
-		log.Errorf("split host port fail: %s", err)
-		return nil, err
+	hp := strings.Split(key, ":")
+	host := hp[0]
+	//  according to APISIX upstream nodes policy, port is optional
+	port := "0"
```
Comment (bzp2010) [inline api/internal/core/entity/format.go:31]: Is it appropriate to use port 0 by default? Should port 80 be used by default? 🤔

Comment (jwrookie) [reply api/internal/core/entity/format.go:31]: https://github.com/apache/apisix-dashboard/blob/92f46d9d2fa8438659131eedecf9cab4c87b0f9d/api/internal/core/entity/entity.go#L99-L105

We cannot give default values to port, the value of 0 is assigned because the zero value is ignored during `json.Marshal`

Comment (bzp2010) [reply api/internal/core/entity/format.go:31]: image

When there is no port in host, port `0` will be used by default, which I think is wrong. For HTTP it should be `80` and for HTTPS it should be `443`, so I think it should be set to 80 by default.

Comment (jwrookie) [reply api/internal/core/entity/format.go:31]: Port is not required, when using https and not configured port it will cause problems, if we do not configure the port there is no such problem

If 80 is given, you need to determine the schema type, when it is https and then change the port default back to 443. I think the first one is more convenient, what do you think?

Comment (bzp2010) [reply api/internal/core/entity/format.go:31]: So to put it another way, if the port is 0, the JSON will not contain the port field when it is encoded in JSON? The `port` is required.

image

image

**Review by bzp2010 — APPROVED** [review]
