### PR TITLE
fix: unable to export route with nil methods field

### LINKED ISSUE #1668: The route imported through Apisix's interface using Export OpenAPI exported file is empty
## Issue description
I want to synchronize old data, the old apisix version is 1.4.0, and now I use apisix with version 2.4 and apisix-dashboard with version 2.4, etcd with version v3.4.15. 
I use Apisix's interface '/apisix/admin/route' to import my route data, I see it work by apisix-dashboard.
When I use Export OpenAPI to export this route data, the file which I export was empty.
But another route which I create by apisix-dashboard I can export full data to file.
## Expected behavior
I want to export full json data to file using Export OpenAPI function.
The route data is imported by Apisix's interface and not only create by apisix-dashboard.

## How to Reproduce
1、imported route data by Apisix's route api
2、find it on apisix-dashboard
3、choose this route, click Export OpenAPI to export json data
4、see this json file

## Screenshots

image

which one I wish to see:
image

## Environment

* apisix version (cmd: `apisix version`): 2.4 (docker)
* OS (cmd: `uname -a`): centos
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.4 (docker)
* Browser version, if have: Chrome

### PR DESCRIPTION
**Pull request by Jaycean**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

1. Fixed the bug that when creating route, the methods field is nil or [] and the data cannot be exported.

2. When there is no plugin data in the route, the empty field is not exported.

**Related issues**

fix/resolve #1668 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

File: api/internal/handler/data_loader/route_export.go [hunk 1]
```diff
@@ -245,8 +246,14 @@ func (h *Handler) RouteToOpenAPI3(c droplet.Context, routes []*entity.Route) (*o
 		path.RequestBody = &openapi3.RequestBodyRef{Value: requestBody}
 		path.Responses = openapi3.NewResponses()
 
-		for i := range route.Methods {
-			switch strings.ToUpper(route.Methods[i]) {
+		if route.Methods != nil && len(route.Methods) > 0 {
+			routeMethods = route.Methods
+		} else {
+			routeMethods = []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodDelete, http.MethodPatch, http.MethodHead, http.MethodConnect, http.MethodTrace, http.MethodOptions}
```
Comment (tokers) [inline api/internal/handler/data_loader/route_export.go:252]: Can we use a pre-defined unexportable variable to indicate this default method set?

Comment (Jaycean) [reply api/internal/handler/data_loader/route_export.go:252]: Yeah,Because these methods such as "GET", "POST" and so on are immutable, the use here is more uniform, and "Get", "get" and "GET" will not appear.

File: web/cypress/fixtures/export-route-dataset.json [hunk 2]
```diff
@@ -131,7 +129,6 @@
             }
           },
           "x-apisix-enable_websocket": false,
-          "x-apisix-plugins": {},
```
Comment (starsz) [inline web/cypress/fixtures/export-route-dataset.json:134]: Just want to know why delete it?

File: api/test/e2e/route_export_test.go [hunk 3]
```diff
@@ -2505,6 +2503,499 @@ func TestRoute_Export_Equal_URI(t *testing.T) {
...
+					"x-apisix-enable_websocket": false,
+					"x-apisix-hosts": ["test.com"],
+					"x-apisix-priority": 0,
+					"x-apisix-status": 1,
+					"x-apisix-upstream": {
+						"nodes": {
+							"172.16.238.20:1980": 1
+						},
+						"type": "roundrobin"
+					}
```
Comment (starsz) [inline api/test/e2e/route_export_test.go:2918]: They are the same. Can we use a variable instead?

```
                                        "requestBody": {},
					"responses": {
						"default": {
							"description": ""
						}
					},
					"x-apisix-enable_websocket": false,
					"x-apisix-hosts": ["test.com"],
					"x-apisix-priority": 0,
					"x-apisix-status": 1,
					"x-apisix-upstream": {
						"nodes": {
							"172.16.238.20:1980": 1
						},
						"type": "roundrobin"
					}
```

Comment (Jaycean) [reply api/test/e2e/route_export_test.go:2918]: Here, I intend to modify it uniformly when using ginkgo rewriting.

File: web/cypress/fixtures/export-route-dataset.json (hunk 2 above)
Comment (Jaycean) [reply web/cypress/fixtures/export-route-dataset.json:134]: The design of import and export is to export when there is data, and not export when there is no data. Here, no data is empty. I don't think it's necessary to export, so I delete it.

Comment (Jaycean) [reply web/cypress/fixtures/export-route-dataset.json:134]: If it is not deleted, Fe ci will report an error.

Comment (nic-chen) [reply web/cypress/fixtures/export-route-dataset.json:134]: @Jaycean do we have some test case for `x-apisix-plugins` not empty ?

Comment (Jaycean) [reply web/cypress/fixtures/export-route-dataset.json:134]: Yes, most of the other test cases have data in `x-apisix-plugins`
For example, this test case: 
https://github.com/apache/apisix-dashboard/blob/73e96357c64ddc92551854577879b86a4ecee341/api/internal/handler/data_loader/route_export_test.go#L34

File: api/internal/handler/data_loader/route_export.go (hunk 1 above)
Comment (tokers) [reply api/internal/handler/data_loader/route_export.go:252]: I mean creating a variable `_allHTTPMethods`, which is:

```go
var (
    _allHTTPMethods = []string{http.MethodGet, http.MethodPost, ...}
)
```

File: web/cypress/fixtures/export-route-dataset.json (hunk 2 above)
Comment (starsz) [reply web/cypress/fixtures/export-route-dataset.json:134]: Thank you for the explanation.Got it.

File: api/test/e2e/route_export_test.go (hunk 3 above)
Comment (starsz) [reply api/test/e2e/route_export_test.go:2918]: Got it.

File: api/internal/handler/data_loader/route_export.go (hunk 1 above)
Comment (Jaycean) [reply api/internal/handler/data_loader/route_export.go]: Sorry, I misunderstood.
Done. Thks

**Review by tokers — APPROVED** [review]

File: api/internal/handler/data_loader/route_export.go [hunk 4]
```diff
@@ -233,7 +235,7 @@ func (h *Handler) RouteToOpenAPI3(c droplet.Context, routes []*entity.Route) (*o
 			return nil, err
 		}
 
-		if plugins != nil {
+		if len(plugins) > 0 {
```
Comment (nic-chen) [inline api/internal/handler/data_loader/route_export.go:238]: how about add `plugins != nil &&`

Comment (Jaycean) [reply api/internal/handler/data_loader/route_export.go:238]: It was written in the past(commit:https://github.com/apache/apisix-dashboard/pull/1673/commits/6dd85785cd752539b0ec50652e68e1f34ef1cf56), but go-link will report error, so it was modified according to go-link.

Comment (nic-chen) [reply api/internal/handler/data_loader/route_export.go:238]: ok..

**Review by nic-chen — APPROVED** [review]

**Review by starsz — APPROVED** [review]
