### PR TITLE
fix: conflicted when update global rule

### LINKED ISSUE #1149: Bug: get 'key: xxxx is conflicted' message when PUT global rules
# Bug report

## Describe the bug
Get 'key: xxxx is conflicted' error message when PUT global rules

## Expected behavior
PUT `global_rules` successfully

## Screenshots
image
image

## System information

- OS: [e.g. macOS]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [master]

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
close #1149
___
### Bugfix
- Description

Get 'key: xxxx is conflicted' error message when update a global rule

- How to fix?

Replace `Create` with `Update` and set `createIfNotExist` to not true

### CODE REVIEW

File: api/test/e2e/global_rule_test.go [hunk 1]
```diff
@@ -56,7 +56,6 @@ func TestGlobalRule(t *testing.T) {
 			Path:   "/apisix/admin/global_rules/1",
 			Method: http.MethodPut,
 			Body: `{
-                                "id": "1",
```
Comment (starsz) [inline api/test/e2e/global_rule_test.go:59]: Why this line should be deleted?

Comment (nic-chen) [reply api/test/e2e/global_rule_test.go:59]: We support no ID in body. Deleted to test this scenario

**Review by membphis — APPROVED** [review]
LGTM

**Review by LiteSun — APPROVED** [review]
